### ISSUE TITLE
Third Person: AA Not Showing

### ISSUE THREAD

**Issue by Slyember** [danielkrupinski/Osiris#1010]
Third Person does not show the AA at all and only shows if we use "bot_mimic 1" on a server.

A "getviewangles" hook is needed :D

**Comment by notgoodusename** [comment]
bruh i just check Engine.h and there is a func called "getViewAngles", at line 44

**Comment by xAkiraMiura** [comment]
1. go to hkDrawModelExecute
2. get the struct that has the view angles (ModelRenderInfo& type)
3. somehow check if it is the local player (maybe compare viewangles?)
4. replace the struct's angles with cmd angles.


normally cmd angles get set to our engine angles every tick however certain things like AA or aimbot overwrite the cmd angles without changing the engine angles. DME is based on our engine angles rather than our cmd angles so we need to change that.

_you can get cmd angles in hkCreateMove_

**Comment by notgoodusename** [comment]
> 1. go to hkDrawModelExecute
> 2. get the struct that has the view angles (ModelRenderInfo& type)
> 3. somehow check if it is the local player (maybe compare viewangles?)
> 4. replace the struct's angles with cmd angles.
> 
> normally cmd angles get set to our engine angles every tick however certain things like AA or aimbot overwrite the cmd angles without changing the engine angles. DME is based on our engine angles rather than our cmd angles so we need to change that.
> 
> _you can get cmd angles in hkCreateMove_

so did you made it?(desync chams)

**Comment by xAkiraMiura** [comment]
i haven't figured out step 3, if i did, i would make them. comparing view angles is prone to failure so i want to find a better method first.

**Comment by notgoodusename** [comment]
> i haven't figured out step 3, if i did, i would make them. comparing view angles is prone to failure so i want to find a better method first.

there is a gucci method
 if (info.entityIndex == interfaces.engine->getLocalPlayer())
if (std::strstr(info.model->name, "models/player"))

**Comment by xAkiraMiura** [comment]
> 
> 
> > i haven't figured out step 3, if i did, i would make them. comparing view angles is prone to failure so i want to find a better method first.
> 
> there is a gucci method
> if (info.entityIndex == interfaces.engine->getLocalPlayer())
> if (std::strstr(info.model->name, "models/player"))

ah i didn't know `ModelRenderInfo` had the entity index, i'll make the chams when i get some free time.
^ developing is really slow because i have to restart the game every iteration. if someone could make it properly unload so LoadLibrary works multiple times that would be great.

**Comment by effex1337** [comment]
1. interfaces.engine->getViewAngles() gives the angle where u aiming at(not rly sure)
2. Loadlib isnt supposed to work like that(unload)

**Comment by xAkiraMiura** [comment]
>     1. interfaces.engine->getViewAngles() gives the angle where u aiming at(not rly sure)
> 
>     2. Loadlib isnt supposed to work like that(unload)

correct, engine angles are what the player sees on their monitor
cmd angles are what everyone else sees.

Osiris doesn't support reinjection because it's never fully unloaded, LoadLibrary will only inject a DLL if it isn't already loaded.
^ side effect with this is even if we unload then VAC might still see the Osiris.dll is loaded in memory and detect it.
