### ISSUE TITLE
fakelag viewmodel fix

### ISSUE THREAD

**Issue by m0rethan3** [danielkrupinski/Osiris#1028]
are you planning to implement such feature?
like when you pull out weapon with fakelag enabled it lags for second

**Comment by Straightplus** [comment]
bruh

**Comment by Straightplus** [comment]
bruh moment

**Comment by m0rethan3** [comment]
i mean there is already fix in some p2c cheats and that post on unknowncheats.me https://www.unknowncheats.me/forum/2409532-post5.html

**Comment by xAkiraMiura** [comment]
*is this pasting i see?*

just set bSendPacket to true is changing weapons.

**Comment by m0rethan3** [comment]
this makes no sense i dont want to unlag to fix animation issue
proper fix shouldnt do like that

**Comment by xAkiraMiura** [comment]
If you fix the animation you will still be desynchronized (bad) for the duration of your fakelag - how far into the current "cycle" you are.
I don't know about you but if im running at 5 ticks of fake lag I would rather just tell the server what I'm doing for 1 tick rather than desyncing for 1-4 ticks.
^ on top of that you will have to wait an additional *n* ticks because the server thinks you only just now pulled out your weapon.

**Comment by m0rethan3** [comment]
thanks for explanation but your way is right for legit cheating otherwise in rage hvh you can get shot in your head for such unlag

**Comment by xAkiraMiura** [comment]
in what world are you swapping weapons right in front of someone.

**Comment by m0rethan3** [comment]
switching to taser or switching to pistol when primary weapon ammo is out for example

**Comment by xAkiraMiura** [comment]
either way you're still going to have to go through the entire drawing out sequence, just 1 is offset by a few ticks.
