### ISSUE TITLE
Anti Aim Grenades

### ISSUE THREAD

**Issue by mapleint** [danielkrupinski/Osiris#1185]
Anti aim grenades maintain yaw but are distorted to the value set in pitch

**Comment by Vonr** [comment]
what?

**Comment by xAkiraMiura** [comment]
when your character is about to release the grenade start holding LMB.

the issue is that the anti-aim doesn't check if you are throwing a grenade, it only checks if you have IN_ATTACK pressed. throwing a grenade has a delay so by the time you actually throw it the AA no longer thinks you are holding IN_ATTACK and starts looking down again.

we've (not me) tried to fix it in the past but every attempt has introduced an edge case which would crash.

**Comment by JDeu** [comment]
> every attempt has introduced an edge case which would crash.

No it hasn't? Just add a `nullptr` check.

**Comment by xAkiraMiura** [comment]
i think in effex's pull they did that but it never got accepted due to another crash.

**Comment by effex1337** [comment]
They're wasn't any crash.
It never got accepted cuz the anti aim never really worked properly so it was pretty much useless.
