### ISSUE TITLE
Toggle on menu click

### ISSUE THREAD

**Issue by LuanDevecchi** [danielkrupinski/Osiris#12]
Hi,

currently, if we click on any option on the menu it will set its visibility to true, what about toggling it? so we can show/hide also.
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/GUI.cpp#L41 

This and a strcpy insecure function warning was fixed on 
https://github.com/LuanDevecchi/Osiris/commit/b8deac7144474be88f9be6b43e37eba713c3fe80

since i don't know if you plan to do this, or if you like the macro idea, i'm opening this issue.
if you want to receive a pull request just let me know

**Comment by danielkrupinski** [comment]
Hello, the idea of toggleable menu items appeals to me, but we already have an 'X' in upper right corner of every window. Should it be removed or keeped? Also I think when window is active, toggle should change it's color. I don't like preprocessor macros, epecially defined in headers, toggles should be implemented directly in ** GUI.cpp**.

Strcpy warning fix is nicely done, but I thought about ommiting buffer and directly writing to std::string (which would require some work because of C-style imgui api).

**Comment by danielkrupinski** [comment]
I have implemented basic window toggling: fe85ee9f450bb191acb02bb38195146e3b76aa2a - a little simpler than yours.

**Comment by LuanDevecchi** [comment]
Seems perfect for me.
you can close the pr!
