### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Keiserin0** [danielkrupinski/Osiris#120]
Add Smoke check to aimbot as well [√]
Add Weapon ESP
Add Draw FOV
Add bind to mouse 4 /  5 for triggerbot
Add grenade trajectory
Add Bomb Timer
Add Logs [ Damage to player , Buy Log ]
Add ESP smoke check
-is it possible to increase range for triggerbot?

**Comment by Asado-san** [comment]
Yeah.! nice Suggestion mate.
especially on Draw Aimbot FOV  & Grenade Trajectory.
we really need those.
@EGTLoneWolf 

also on " Weapon ESP " please add ESP Range Limit slider, since it's very annoying to have 
it constantly turned on in Danger  Zone, " Kill button " would also work like " delete button "
@danielkrupinski
