### ISSUE TITLE
Questions on certain features

### ISSUE THREAD

**Issue by Adim2P** [danielkrupinski/Osiris#1289]
What does Max Angle Delta, Choked Packets do? I did read the introduction for it but I'm still confused

And what are the difference between Pitch and Yaw in anti aim?

**Comment by ClaudiuHKS** [comment]
**Anti Aim Pitch** : You look at the sky or at the ground.
**Anti Aim Yaw** : It works when Chocked Packets **NOT** 0, you look +90 deg. to the right or something like that.
**Maximum Angle Delta** : Maximum view angle delta change per tick. This is good for Casual, Death Match, Gun Game and Arms Race game servers so you don't get kicked with the message **VAC was unable to ...**. It's important not to mix Anti Aim with Maximum Angle Delta. Use Maximum Angle Delta 255.0 when Anti Aim is enabled.
**Chocked Packets** : Fake lag.

**Comment by Adim2P** [comment]
> **Anti Aim Pitch** : You look at the sky or at the ground.
> **Anti Aim Yaw** : It works when Chocked Packets **NOT** 0, you look +45 deg. to the right or something like that.
> **Maximum Angle Delta** : Maximum view angle delta change per tick. This is good for Casual, Death Match, Gun Game and Arms Race game servers so you don't get kicked with the message **VAC was unable to ...** It's important not to mix Anti Aim with Maximum Angle Delta. Use Maximum Angle Delta 255.0 when Anti Aim is enabled.
> **Chocked Packets** : Fake lag.

So, is Yaw more useful than Pitch in an HvH situation? Or it works kinda the same with the Pitch?

**Comment by ClaudiuHKS** [comment]
I think Yaw is more useful in Osiris because it won't change your angles that much and it won't look that obvious in a Demo or to Spectators. Pitch is really obvious.

Also, I think Yaw can work with Max. Angle Delta set to 30.0 or 45.0 as well. And you won't get kicked in a Death Match, Arms Race, Gun Game or Casual game server (VAC was unable to ...) for using Anti Aim Yaw.

In a HVH situation, both Pitch and Yaw are important and especially while used together. It's very important your enemy to miss you, so you can kill him.

**Comment by xAkiraMiura** [comment]
`bot_mimic 1` makes bot's mirror your viewangle.

back when i made my anti-aim expansion i tried to test the current anti-aim and i couldn't miss when manually aiming.
