### ISSUE TITLE
[Request] Ragdolls for chams.

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#1299]
I mean, we have ragdolls applied for glow already, why not add to chams too, and I think I see some issue about this and people said add to chams is more complicated and need more than just applied simple code, like glow to chams.

But anyways, I this it's a good thing to add.
- [Exemple](https://imgur.com/a/WITVlwF).

**Comment by dapaster** [comment]
404 - image not found!

**Comment by xAkiraMiura** [comment]
chams are a DrawModelExecute thing because they use materials.
ragdolls don't pass through DME. (we can prove this by hooking it and returning without calling the original, all players will be invisible yet ragdolls still render, even while in motion)

i saw a thread on UC but i don't know if it allows you to modify the material.

**Comment by rosesware** [comment]
> 404 - image not found!

Updated.

**Comment by suddenlybydl0** [comment]
> chams are a DrawModelExecute thing because they use materials.
> ragdolls don't pass through DME. (we can prove this by hooking it and returning without calling the original, all players will be invisible yet ragdolls still render, even while in motion)
> 
> i saw a thread on UC but i don't know if it allows you to modify the material.

There is a fix on UC - https://www.unknowncheats.me/forum/counterstrike-global-offensive/366471-dme-weapon-chams.html
