### ISSUE TITLE
Backtrack skips 1 tick whenever i shot

### ISSUE THREAD

**Issue by HugeSwantz** [danielkrupinski/Osiris#1346]
The backtrack literally misses 1 tick when i shot
![ezgif-2-0b77b8f9fe1a](https://user-images.githubusercontent.com/53080752/77948479-c2c47480-72c5-11ea-985f-2d309bfe5af4.gif)

**Comment by streamshark** [comment]
I can't see your crosshair/where you are aiming at all

**Comment by RyDeem** [comment]
thatz not the point streamshark, look at the screenshake for shooting, the backtrack is skipping 4 sure.

**Comment by HugeSwantz** [comment]
yes it skips 1 tick im certain but thats not all because of my capture software i wasnt able to show u guys that in that time frame when it skips all other dont work and i miss :(

**Comment by DoomFishWasTaken** [comment]
Let me explain this to you. 
`cmd->tickCount = timeToTicks(record.simulationTime + getLerp());`
this is the line where the backtrack is applied, `cmd->tickCount` is current client tick (sent every 1s / sv_mincmdrate). So basically backtrack tells the server that you are `timeToTicks(entity->simulationTime() - record.simulationTime);` behind the server and you shot the enemy,
because you can't tell the server that you shot twice in a single tick, one tick is skipped (note if I got something wrong I apologize, this is just my understanding of backtrack)
