### ISSUE TITLE
When do i need to re-install Osiris?

### ISSUE THREAD

**Issue by tdux** [danielkrupinski/Osiris#1386]
Hello, i downloaded Osiris i few days ago, and i use VMProtect in the DLL file. I wanted to know how often do i have to re-install the DLL and do the process of protecting the it all again. Is it just when the DLL is updateded or on every minor ZIP changes? Thank you for the support.

**Comment by Vadenez** [comment]
@danielkrupinski updates Osiris almost everyday, so its your choice if you want a newer version or not. personally I update my DLL every week on a sunday.
Also idk what you mean by:
>Is it just when the DLL is updateded or on every minor ZIP changes?

Cus as far as I know its always a change to the ZIP and in those changes after you have compiled it to a DLL, the DLL is effectively "updated". Unless you mean a "release" coming out so that you don't have to compile, but so far as I know the DLL have never been realeased derectly in DLL form. So, you will always have to compile it in VS 2019.

Hopfully this helped :)

**Comment by tdux** [comment]
I got, Thank You!
