### ISSUE TITLE
Csgo clantag [Please help]

### ISSUE THREAD

**Issue by lelo0577** [danielkrupinski/Osiris#1402]
Hello guys, so i was coding an external clan tag for csgo to sync with my other friend and i was trying to make it as exe file .. but somehow its not working any idea ? 

Discord: LELO#0577

Thanks

**Comment by KernCS** [comment]
why not just make a clantag for Osiris and make it sync?

**Comment by danielkrupinski** [comment]
Use UserCmd::tickcount or GlobalVars::currenttime.

**Comment by lelo0577** [comment]
Daniel i didnt get it :( 

and also KernCS can you add me on discord and teach me ?

**Comment by KernCS** [comment]
> teach

teach you what?

**Comment by xAkiraMiura** [comment]
their question is *probably* irrelevent from Osiris entirely, unless they want to convert it to an executable instead of a DLL, otherwise they want to make a standalone **external** with a clantag changer (which im pretty sure is *internal* exclusive)

you will still have to have a DLL either way, you can just hide it by making a custom loader.

for the clantag changer you do the substring operation based off the current tick count or system time.

**all the information you need to make a synced clantag changer is inside this issue**, brain not included.
