### ISSUE TITLE
Overwatch Bypass Config Osiris

### ISSUE THREAD

**Issue by Araptois** [danielkrupinski/Osiris#1464]
Inspired by this config (here : https://www.youtube.com/watch?v=Oex9kmj_cyQ

I have made an even more legit one that gives non-negligible benefits, all in the right dosage. 

Disclaimer: Don't use this config if you're not good at playing without cheat, this config won't give you super powers either, you'll just be better.

Don't use chams/wallhack/glow, you're likely to get banned overwatch, as well as the player's field of view or the triggerbot, even with great care, that's why my config doesn't contain any.

You can activate the bhop, but use it sparingly. I let you discover the rest of the config, good game to you.

https://anonfile.com/Lcy8Qdr6oc/fullegit

**Comment by tirziz** [comment]
Valve has been flagging people with aimbot since, I don't think its a good idea to use aimbot if you want super legit.

**Comment by Araptois** [comment]
> 
> 
> vacnet has been flagging people with aimbot since, I don't think its a good idea to use aimbot if you want super legit.

Really, since when? In my config the FOV is super low (0.40), I don't know if it can be flagged by vacnet

**Comment by vsnrytune** [comment]
> > vacnet has been flagging people with aimbot since, I don't think its a good idea to use aimbot if you want super legit.
> 
> Really, since when? In my config the FOV is super low (0.40), I don't know if it can be flagged by vacnet

That's a bit OTT, I play with 1.5-2 fov on rifles and smg's with 12 smooth and 2.5 on pistols with 8 smooth, for pistols bone is set to head and rifles/smgs to sternum and it's literally undetectable as long as your movement and everything else is great and you don't use wallhack.

I also have standalone rcs code in my osiris paste which makes it look even more legit. I've played like 5-10 matches a day for months with the same config and no ban

**Comment by xpossed-you** [comment]
its never the config that bypass OW because you will get OW when someone is reporting you and not just 1 person.. if too many player report you, your CSGO account will get Untrusted and will matched up againts well C H E A T E R. im using aimbot, wallhacks(chams, glow, ESP) player who use the cheat  is the problem, remember config doesnt bypass OW

**Comment by Shaxzy** [comment]
> if too many player report you, your CSGO account will get Untrusted and will matched up againts well C H E A T E R.

No offense but I call bullshit on this lol.
I've been cheating in csgo since 2015 and I have never once gotten an untrusted ban. And I can assure you I get reported every game*. I was even blacklisted in bansystem and zonerbot on some of my accounts for a limited time. That means I got reportbotted literally every game I played (I checked it myself, bots were connected and matched with the logs. Not some fake reportbot). 

Also to mention I'm green trust on my main, as well on my 4 alt/semirage prime accounts. I've been green for about 1 year now. Reports doesn't affect my trustfactor. One of my accounts dropped to red trust for a short period of time after I got grief banned. After playing a few matches I was green again. 

You're obviously spreading false information. I have NEVER heard of anyone nor gotten myself an untrusted ban due to reports. If it worked like that anyone could reportbot an innocent player and boom, untrusted ban. Untrusted bans are usually applied due to unclamped angles, injectors etc. Reports won't get you untrusted banned nor will it get you matched against cheaters, BUT it can very well affect your trustfactor, which yes might get you matched up against other cheaters but not necessarily. For me personally reports doesn't affect my trustfactor but I have friends who gets red again after x amount of reports. Last time I got banned on a prime accounts was more than a year ago. Afaik vacnet detects banned accounts or something from your pc which might affect your trustfactor. I must have been in overwatch many times without getting banned because I know very well how to hide it. Overwatch can't prove that I am cheating. I think this is why I'm solid green, but what do well I know.

Now if you for some reason don't believe me or whatever lmk. I can of course prove all of this, link my accounts and have people vouch for me.
I thought you should also know that I don't use Osiris. I've been using gamesense for more than one year until I got forum banned a little while back. After that I've been using novolinehook until this day (no sub right now as I'm only playing call of duty).

*I semirage pretty hard in matchmaking every game. legit antiaim, magnettrigger, clantag, name spam and other lua scripts for the memes. I couldn't care less about reports honestly. I also usually always queue in a 5 man cheater stack which again leads to the enemy team report us all most games.

**Comment by Or3nges** [comment]
@Shaxzy I think he meant a red trust factor instead of untrused. If too many players report u then your trust factor will be lower and lower. U can't see your trust factor but other member of your lobby can. If their trust factor is also red, then they won't get a message and they'll think that they're green. keep in mind that other factors in-game and outside can impact your trust factor greatly (ex. new account, rank, playtime, etc). Untrusted bans can only happen if vac detects your shitty public injector or the injection is detectable. U can also get a untrusted ban if you have a bad coded aa (unclamped angles) or a bad coded aimbot. Congratulations for hiding your cheats really good and having no overwatch bans.

**Comment by furioushell98** [comment]
> >vacnet has been flagging people with aimbot since, I don't think its a good idea to use aimbot if you want super legit.
Not possible. My legit settings are 1.64 fov rifles and 1.92 fov pistols, 90ms backtrack and i never got banned. Also i've used semirage osiris config for a month on prime alt without getting banned. I literally get reported every match and nothing happens. If you don't use Autowall/very high fov/rage and aa it's really hard to get banned.
[Semirage cfg (https://cdn.discordapp.com/attachments/697676786288558110/701229632829259896/semirage)
[Legit cfg](https://cdn.discordapp.com/attachments/697676786288558110/701229643596038154/Beast_Mode)
Used both of these on main and alt for 200 hours or more. never been banned.

**Comment by Shaxzy** [comment]
@Or3nges Fair enough. I was drunk when I read it lol
