### ISSUE TITLE
Legit Aim Settings

### ISSUE THREAD

**Issue by bekocango** [danielkrupinski/Osiris#1536]
I will use those settings, legit???
1.5-2 fov with 12 smooth on rifles and 2-2.5 fov with 8 smooth on pistols and aimlock on on both. 
1920x1080 screen. (I will use this on my main acc.) Thanks...

**Comment by HowToMakeFaceitAB** [comment]
um not for the most part, if you're gonna use aimlock decrease fov to < 1.5 and on pistols use around 1.8 - 2.0 with >12.5 smooth, should look legit enough that you won't get banned on overwatch. the problem is that with these settings on a new account people will call you out for cheating because of how bad they are

**Comment by lordeternity000** [comment]
I use 1.1 fov rifles, smg with 2.5 smooth and aimlock. and pistols you should be below 1 fov for low or 1 smoothing but high smoothing on pistols with 1.5 is fine.
