### ISSUE TITLE
ready config

### ISSUE THREAD

**Issue by toprak1224** [danielkrupinski/Osiris#1616]
Configin ready I want it to come, what should I do? get ready when the cheat opens

**Comment by toprak1224** [comment]
PLSS SOMONE HELP ME

**Comment by KernCS** [comment]
idk if this is what u wanna have but at the bottom of
> Hooks::Hooks(HMODULE cheatModule) : module{ cheatModule }
Paste config->load(0);

![wnBt5Uf](https://user-images.githubusercontent.com/31683300/82612398-0dc28000-9bc3-11ea-932a-a5589c49cffe.png)

(don't mind mine is called skinconfig i got normal cfg & config only for skins)

**Comment by imbarismustafa** [comment]
Thant would be cool tbh. I am new to the project too and trying to understand where the config files are stored. It says in Documents folder but there is no config file. Ideally a user would like to configure the settings and even after a restart, the dll file should automatically check for preconfigured user preferred settings. Like enable x,y,z settings so that when in the game, there is no need for configuration.
