### ISSUE TITLE
Pc Shut down problem

### ISSUE THREAD

**Issue by bootfast** [danielkrupinski/Osiris#1806]
After injecting osiris, i cant shut down my pc...
Any solution?

**Comment by xXTOO-HARDXx** [comment]
I really don't see how this could be anything to do with Osiris.

But, something you can try; **open Task Manager and see if there's an idle csgo.exe process running after you close the game, that might be a possible solution**

**Comment by ocewot** [comment]
process hacker 2 user lol, its cause by ph2

**Comment by newcommerdontblame** [comment]
> process hacker 2 user lol, its cause by ph2

Nah??

**Comment by xXTOO-HARDXx** [comment]
> process hacker 2 user lol, its cause by ph2

No, I very highly doubt it.

**Comment by hyperxpro** [comment]
Just cut the power supply. :D

**Comment by king1919djdj** [comment]
I use ph2 it doesn't cause such issues

**Comment by MiniPEACECloset** [comment]
It's process hacker interfering with the shutdown.exe, logoff.exe, restart.exe and hibernate.exe

**Comment by MiniPEACECloset** [comment]
Try updating your windows. 1903 windows version it was caused. but probably fixed in 1906 and 1909.

**Comment by xXTOO-HARDXx** [comment]
> It's process hacker interfering with the shutdown.exe, logoff.exe, restart.exe and hibernate.exe

I very highly doubt it. Process Hacker is a UserMode process. It would not be interfering with any system calls. The kernel driver won't stop the shutdown either.

> Try updating your windows. 1903 windows version it was caused in. but probably fixed in 1906 and 1909.

And also no, why would Microsoft updates make any difference for a third party piece of software.

**Comment by xXTOO-HARDXx** [comment]
> It's process hacker interfering with the shutdown.exe, logoff.exe, restart.exe and hibernate.exe

I very highly doubt it. Process Hacker is a UserMode process. It would not be interfering with any system calls.

EDIT: It actually might be Process Hacker, because of the Kernel Driver. if you are using Windows version 1803 or something that isn't the latest update, the driver sometimes refuses to run unload at first for some reason, it holds onto a reference in memory. The solution is to just wait apparently.

Sorry @MiniPEACECloset , you were right.
