### ISSUE TITLE
issue with interfaces

### ISSUE THREAD

**Issue by AustScar5** [danielkrupinski/Osiris#1810]
i've noticed in the latest builds of osiris that there's an error with initializing interfaces
'pointer to incomplete class type is not allowed'

**Comment by xXTOO-HARDXx** [comment]
I also get this error, and it's annoying, albeit it only happens when you have another error or sometimes just randomly, without reason.
I think it's the compiler not finding the references because they are linked later when the linker pass goes ahead.

What works for me is closing all code windows (hooks.cpp, etc.) inside of the VS UI, cleaning the solution, making sure you have no errors OTHER than the interfaces pointer errors, and then trying to compile again.

**Comment by danielkrupinski** [comment]
That's only Intellisense bug, it doesn't affect compilation.
