### ISSUE TITLE
[cheat issues] 

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1816]
1. Smooth type is not static ( the smooth slows down the closer you are to enemy hitbod)

2. Aimbot tries to rcs with USP

3. The rcs isn't good at all, it's not even an rcs, better off pasting some standalone rcs off of UC than to use whatever this shit is

4. No lby breaker for legit aa

5. Aa isn't customizable at all, better off just removing it if you're not gonna change it

6. The aimbot doesn't allow you to select multiple hitboxes and that kinda sucks

7. The backtrack isn't good at all ( i don't think it's even close to 12 ticks of bt to be honest) 

8. Aimbot doesn't shoot head if backtrack enabled 

9. Auto fire and triggerbot doesn't have any form of trace ray hitchance (used for rage hacking)

10. Trace ray better than inaccuracy, maybe replace inaccuracy with trace ray?

**Comment by DoomFishWasTaken** [comment]
4. There is pulls eg. #1546
5. Same as 4.
6. Adding that soon to my pull #1546 
7. You can't backtrack more, well you can but I haven't added that it's kinda complex, you have to move forwardtracking window into backtrack ;)

**Comment by Scui1** [comment]
>     4. You can't backtrack more, well you can but I haven't added that it's kinda complex, you have to move forwardtracking window into backtrack ;)

Wtf are you talking about. He didn't mean 12 ticks is not enough, but Osiris mostly doesn't even backtrack 12 ticks.
And even if you wanted to increase the backtrack window, you would just fake your ping to the server. Forwardtracking is kinda useless in my opinion.

**Comment by wirebruh** [comment]
9. It's a legit cheat, and it's open source, so pasting someone's code is not that hard to do.

**Comment by xXTOO-HARDXx** [comment]
> 1. Smooth type is not static ( the smooth slows down the closer you are to enemy hitbod)
> 2. Aimbot tries to rcs with USP
> 3. The rcs isn't good at all, it's not even an rcs, better off pasting some standalone rcs off of UC than to use whatever this shit is
> 4. No lby breaker for legit aa
> 5. Aa isn't customizable at all, better off just removing it if you're not gonna change it
> 6. The aimbot doesn't allow you to select multiple hitboxes and that kinda sucks
> 7. The backtrack isn't good at all ( i don't think it's even close to 12 ticks of bt to be honest)
> 8. Aimbot doesn't shoot head if backtrack enabled
> 9. Auto fire and triggerbot doesn't have any form of trace ray hitchance (used for rage hacking)
> 10. Trace ray better than inaccuracy, maybe replace inaccuracy with trace ray?

1. That's literally what it's meant to do, a smoothing aimbot, or linear aimbot, uses Linear Interpolation (Read [Linear Interpolation](https://en.wikipedia.org/wiki/Linear_interpolation#:~:text=The%20basic%20operation%20of%20linear,two%20endpoints%20of%20the%20line.%22))
2. I've told you this before, that's how it's meant to work, it isn't an issue, the USP **has** recoil. You can easily fix that yourself or add a checkbox to incorporate the idea, if you can be bothered.
3. That is partially subjective, and I disagree. There is no 'better' RCS system, the RCS system works by countering the predefined patterns, there's no way to make a legit aimbot any better, unless you use prediction seed.
4. That isn't an issue.
5. Do it yourself, this is an open source project, no one else is complaining.
6. Easily implemented, do it yourself. Again, an open source project that he Daniel isn't getting paid for, stop complaining.
7. This isn't a premium cheat and the backtrack worked fine for me in the past, so I am not sure what your problem is.
8. Incorrect observation.
9. This isn't a rage cheat.
10. Depends on the context, I believe Daniel is doing it right where it should be done.

**Comment by HowToMakeFaceitAB** [comment]
Hmmm, 2. I never said that the usp doesn't have recoil, it has recoil when fired constantly (autofire) problem is nobody fires it auto, i told you this before and you're still not accepting the fact, i fixed all these problems myself, im asking Daniel to it for the general public that don't know how to code or are trying to learn how to, or just people who want to use a free cheat without being bothered to change source, not everyone knows how to code

**Comment by HowToMakeFaceitAB** [comment]
4. How is that not an issue, lby breaker is necessary to extend desycn to +58 or - 58

**Comment by cailloubr** [comment]
Simple, make a pull request with the solutions, for that there is open source.

**Comment by xXTOO-HARDXx** [comment]
> Hmmm, 2. I never said that the usp doesn't have recoil, it has recoil when fired constantly (autofire) problem is nobody fires it auto, i told you this before and you're still not accepting the fact, i fixed all these problems myself, im asking Daniel to it for the general public that don't know how to code or are trying to learn how to, or just people who want to use a free cheat without being bothered to change source, not everyone knows how to code

You're still incorrect, then. I am not accepting no "facts", because they are plain wrong, sorry.

The first shot from a USP still has recoil. That's a fact. Watch the gun and the screen change transform when you shoot, duh.

> 1. How is that not an issue, lby breaker is necessary to extend desycn to +58 or - 58

Huh? extending **ANTIAIM** (Osiris doesn't have **desync**) to +/- 58 IS a preference. Hence, why it's not an issue.

**Comment by xXTOO-HARDXx** [comment]
Just close this issue, Daniel isn't going to make these changes himself. You'll have to request a pull to see any changes to the public code. GL

**Comment by danielkrupinski** [comment]
I've checked the USP aimbot and it doesn't makes your first shot inaccurate.

**Comment by HowToMakeFaceitAB** [comment]
> > Hmmm, 2. I never said that the usp doesn't have recoil, it has recoil when fired constantly (autofire) problem is nobody fires it auto, i told you this before and you're still not accepting the fact, i fixed all these problems myself, im asking Daniel to it for the general public that don't know how to code or are trying to learn how to, or just people who want to use a free cheat without being bothered to change source, not everyone knows how to code
> 
> You're still incorrect, then. I am not accepting no "facts", because they are plain wrong, sorry.
> 
> The first shot from a USP still has recoil. That's a fact. Watch the gun and the screen change transform when you shoot, duh.
> 
> > 1. How is that not an issue, lby breaker is necessary to extend desycn to +58 or - 58
> 
> Huh? extending **ANTIAIM** (Osiris doesn't have **desync**) to +/- 58 IS a preference. Hence, why it's not an issue.

you seem to be new, the screen shake is just visual punch effect that happens with all weapons, you're wrong and you dont wanna accept it

**Comment by HowToMakeFaceitAB** [comment]
> I've checked the USP aimbot and it doesn't makes your first shot inaccurate.

ah yes i was using an older version of osiris and it was innacurate but now it seems to be working well
