### ISSUE TITLE
(Request) Dead Body chams/rag doll chams

### ISSUE THREAD

**Issue by unreasonablehitbox** [danielkrupinski/Osiris#1853]
Ye like the title says, can someone bother adding rag doll chams because I’m a bit lost cause for coding. I tried adding stuff but like so many errors, even after fixing some there’s stuff that I don’t know about.

**Comment by koahook** [comment]
You can attempt to create this by looking at ragdoll and glow and recreate it for chams

**Comment by 0suddenly0** [comment]
You won’t be able to make ragdoll chams since ragdoll models don’t go through DME, but you can fix it.
The first way is in this thread - https://www.unknowncheats.me/forum/counterstrike-global-offensive/366471-dme-weapon-chams.html.
The second way is to hook cvar r_drawmodelstatsoverlay (get_bool (idx 13)) and return true when _ReturnAddress () == 85 C0 75 54 8B 0D? ? ? ?. (thanks LNK1181 for this method)
