### ISSUE TITLE
Game Crashing as soon as injected With Manual Map Injcetor

### ISSUE THREAD

**Issue by harshraj21** [danielkrupinski/Osiris#1917]
I DOnt know what the fuck is going on but i tried each adn every thing updated few offsets and signature which i thin was causing the issues.. but i still cant get  the issue.

**Comment by Frouk3** [comment]
use this injector https://cheater.fun/injectors/1245-csh-injector-works-on-the-new-version-of-csgo-free-download.html
and follow the instructions

**Comment by RyDeem** [comment]
> I DOnt know what the fuck is going on but i tried each adn every thing updated few offsets and signature which i thin was causing the issues.. but i still cant get the issue.

use https://processhacker.sourceforge.io/downloads.php

**Comment by Frouk3** [comment]
> > I DOnt know what the fuck is going on but i tried each adn every thing updated few offsets and signature which i thin was causing the issues.. but i still cant get the issue.
> 
> use https://processhacker.sourceforge.io/downloads.php

process hacker is detectable

**Comment by AbhinayNegi** [comment]
> I DOnt know what the fuck is going on but i tried each adn every thing updated few offsets and signature which i thin was causing the issues.. but i still cant get the issue.

Same thing happening with me to. But there is youtube channel where this person give the link to Osiris and otc dll and an injector, and after using that dll and injector its working fine for me, but if I download the latest version of Osiris it again crashes so that's why I am still using that old dll
Link to the video : https://youtu.be/2AbEd8otr_Y

**Comment by harshraj21** [comment]
ok cool ill test and update u guys soon
