### ISSUE TITLE
Game ban in 1h

### ISSUE THREAD

**Issue by cashsignsesh** [danielkrupinski/Osiris#2171]
I know this isn't really a git issue but there also arent many others on here. I'm using a manual map injector & latest osiris public fork. I was game banned in 1h 30 min on a fresh steam account. I think its cause of the injector or because under cs;go play it says From the library of (my banned account)? How do i fix this/what injector do you all use that doesnt get you game banned?

**Comment by JacksonDon** [comment]
Just make own injector, and dont use public source. 
Best answer what you can get.

**Comment by newcommerdontblame** [comment]
https://github.com/AMATEURZ1337/load-lib-injector

Use it for osiris

**Comment by SwagsRGB** [comment]
> 
> 
> I know this isn't really a git issue but there also arent many others on here. I'm using a manual map injector & latest osiris public fork. I was game banned in 1h 30 min on a fresh steam account. I think its cause of the injector or because under cs;go play it says From the library of (my banned account)? How do i fix this/what injector do you all use that doesnt get you game banned?

Use Sazz Injector. Much safer.

**Comment by yaelahrip** [comment]
game banned? u prolly played too blatant haha.

**Comment by vladimirdabic** [comment]
I use RandoInjector.
You have to compile it yourself.

Been injecting with it for a week now still no ban, don't go blatant and you should be good.

**Comment by Floraly** [comment]
Your ban is mostly an injector issue! You need to look for another injector. I never get VAC Ban in 1 hrs. My last ban was 2017 on my Linux cheat because I used an username that cause the ban. Actually I hook csgo with a Kernel Module so VAC on Linux is not a case for me. It took 2012 to 2017 to Ban me and since 2017 no Ban on me. 👍  I use only open source and public cheats and don't have VAC Bans... Even if people complain VAC Bans here it mostly not the cheat that caused it.

**Comment by danielkrupinski** [comment]
There is nothing we can do about it.
