### ISSUE TITLE
Random useless thing

### ISSUE THREAD

**Issue by uzdiiilekk** [danielkrupinski/Osiris#2267]
Can you make a undected loader like novihacks, project infinity and more cheats ? And add ow bypass please 

If you answer me i can send you movement recorder source code

**Comment by piee-kun** [comment]
If you want an Overwatch bypass, just don't play blatantly. I know it sounds stupid but it is what it is. The less reports you get, or the better your config is, the less you get into Overwatch. The loader as far as I know can be "undetected", if you just add a few lines of code and use a good injector.

**Comment by uzdiiilekk** [comment]
I dont play blatantly a play only visible only and skin changer but all people say me cheater and report me and then i get ban ..

**Comment by scarifyFX** [comment]
aimbot_?

**Comment by uzdiiilekk** [comment]
Sometimes i use backtrack 100ms but every time i have visible only and skin changer but all say me “aahahhaha” or “axaxaxaxa” “you are fucking cheater” and then report me ..

**Comment by piee-kun** [comment]
It is pretty obvious when a player is suddenly killed from a place they were a few milliseconds ago you know that right?

**Comment by uzdiiilekk** [comment]
I use it only when enemy turn but i use only visible only

**Comment by piee-kun** [comment]
I can tell you just started cheating, so I have a few tips. Don't use ESP. At all. Just use really bright chams, so you will react quicker, but nothing else. Maybe aimbot, but you need to tweak a lot. Don't use stuff like backtrack, because if you start hitting a player from somewhere they aren't and you have low ping, you will just be accused over and over again.
