### ISSUE TITLE
only errors (visual studio)

### ISSUE THREAD

**Issue by TsuNamiPlayZ** [danielkrupinski/Osiris#2344]
https://prnt.sc/vp119f

last week I was able to compile everything but nothing works since yesterday!

im using visual studio community 2019

**Comment by franiodat** [comment]
can you take a screenshot of the whole screen and solution properties?

**Comment by TsuNamiPlayZ** [comment]
https://prnt.sc/vpalrz

https://prnt.sc/vpambs
https://prnt.sc/vpamrc
https://prnt.sc/vpanit

**Comment by Khajiitos** [comment]
Maybe it has something to do with the name of a variable called module which confuses visual studio as it's also a keyword
https://github.com/danielkrupinski/Osiris/commit/d7372133b93b13a3b58609a2c4b7e3103e00b54c

**Comment by caiocinel** [comment]
> https://prnt.sc/vpalrz

Why the hell are you adding junkcode to the project? Stop wasting your time with this, if you want to differentiate your build from the original, add some features from the "Pull Requests" tab, which will not fail to be detected with Osiris.

Instead of adding dead code that is useless, add a few more things so you can have better fun!
