### ISSUE TITLE
Injecting DLL has no effect neither with CE 7.2 nor DLL Injector

### ISSUE THREAD

**Issue by ElJaviLuki** [danielkrupinski/Osiris#2648]
### **using Cheat Engine 7.2**

Steps:
1. Open **Counter Strike: Global Offensive**.
2. Open **Cheat Engine 7.2**
3. Select `csgo.exe` process: File > Open Process > 'Processes' tab > (Select `csgo.exe`) > Open.
4. Inject DLL: Memory View > Tools > Inject DLL (Ctrl+I) > Open `Osiris.dll` > 'Do you want to execute a function of the DLL?' > No > 'DLL Injected' is shown.
5. Go back to CSGO > press INSERT > No effect!

### **using [DLL Injector](https://dllinjector.net/) in https://dllinjector.net/**

Steps:
1. Open **Counter Strike: Global Offensive**
2. Open **DLL Injector**
3. **DLL Injector**: Select `csgo.exe` > Browse (or drag DLL file) > Open `Osiris.dll` > Inject
4. Go back to CSGO > press INSERT > No effect!

### Click to see my INSERT frustration youtube video:
[![Youtube Video](https://img.youtube.com/vi/myDTvJ_LNmA/0.jpg)](https://www.youtube.com/watch?v=myDTvJ_LNmA)

_Yeah, I wanted to collaborate on this project since this seems to be the best cheat in GitHub so far, and hugely supported._

**Comment by linuxer9** [comment]
I believe cheat engine is detected (did you vac bypassed it ?), 
anways, what "DLL injector" did you use?

**Comment by ElJaviLuki** [comment]
> 
> 
> I believe cheat engine is detected (did you vac bypassed it ?),

**Yes**, you are right, Cheat Engine is detected on VAC secured servers. Anyways this testing account is VAC banned so I use it for these kind of purposes in non-VAC servers or directly offline (with bots), meaning that I do not care about being detected -unless this is what actually could be causing this issue-, i.e. **I did not VAC bypassed it.** Is it strictly needed?

I actually am not a fan of using Cheat Engine for DLL injection but I eventually tried it after a fit of frustration :)

> anways, what "DLL injector" did you use?

**Yes**, "[DLL Injector](https://dllinjector.net/)" (see link) is the -original and creative- name for an actually existing DLL Injector.

**Comment by linuxer9** [comment]
CS GO has a dll injection prevention mechanism "trusted mode or something", you need to patch it in order to inject, I don't know if that "DLL injector" does that.
another way to bypass that is to put your dll in windows folder (seems ridiculous but it actually works!) 
Or, use another dll injector, manual mapping is safer, use [shtreeba ](https://github.com/mdilai/Shtreeba) or [memject](https://github.com/danielkrupinski/MemJect) .
also Process hacker 2 is a good alternative and it won't be detected as it's a software used for a legit purposes, just remember to put your dll's in windows folder.

**Comment by ElJaviLuki** [comment]
@linuxer9 

Yes, I can say that the issue is related to that, since using the -insecure launch parameter allowed me to inject it successfully with both CE and DLL Injector. 

Anyways, I will try what you have stated.

Thanks!
