### ISSUE TITLE
how i can fix silent

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2691]
how i can do when silent turn on smooth set 0

**Comment by KisSsArt** [comment]
smooth 0? angle /= config->aimbot[weaponIndex].smooth; u can't use smooth 0.

**Comment by osirisbigfan** [comment]
why?

**Comment by KisSsArt** [comment]
angle /= 0? what is angle equal to?

constexpr Vector& operator/=(float div) noexcept
    {
        x /= div;
        y /= div;
        z /= div;
        return *this;
    }

i think he meant smooth = 1

**Comment by caiocinel** [comment]
> why?

That is why you need to pay attention to your math classes, it is impossible to divide by 0, dividing by 1 does not affect the value, so this is what you want.

https://en.wikipedia.org/wiki/Division_by_zero

**Comment by HowToMakeFaceitAB** [comment]
> how i can do when silent turn on smooth set 0

smoothness divides the distance between the Target entity and your view angle, it divides that distance by a value, and then changes your eye angle to that value, that is why the aimbot gets slower the closer your crosshair (view angles) is to the target

in short, you can't have 0 smooth because it is impossible to divide anything by 0, diving by 1 does not change the value, so having 1 smooth sets your view angles to the Enemy bone position
