### ISSUE TITLE
About Trust Factor

### ISSUE THREAD

**Issue by leninismus** [danielkrupinski/Osiris#2891]
We can understand that the confidence factor has decreased with the decrease in gamers looking for games. I am using Vac Bypass Loader. I do not activate Aimbot. I do not activate Wallhack. I am the most legit player in the world, but my trust factor is falling nonetheless. I do not see any decrease in my trust factor when I open a new account and do not inject Osiris. Does using this cheat, first of all injecting it hurts the trust factor?

**Comment by WhatsupDanger** [comment]
Trust factor is bind with HWID so if you have previous VAC banned accounts on the same machine it could hurt your trust factor.
Also remember not only you have good trust factor but the enemy who is Closet Cheating (legit cheating) could also have good trust factor.

Some ways to increase/maintain trust factor:
Playing CS:GO and other Steam games
Enable Steam-Guard
Be a positive member of the Steam Community
Abandons/kicks/kicking players/AFK/griefing will reduce your trust factor

all these are assumptions Valve haven't disclosed anything about it.

**Comment by leninismus** [comment]
> Trust factor is bind with HWID so if you have previous VAC banned accounts on the same machine it could hurt your trust factor.
> Also remember not only you have good trust factor but the enemy who is Closet Cheating (legit cheating) could also have good trust factor.
> 
> Some ways to increase/maintain trust factor:
> Playing CS:GO and other Steam games
> Enable Steam-Guard
> Be a positive member of the Steam Community
> Abandons/kicks/kicking players/AFK/griefing will reduce your trust factor
> 
> all these are assumptions Valve haven't disclosed anything about it.

You made a very good point. Yes, I have accounts banned by VAC; so how can I prevent this? I don’t want to format my computer. Is there an app that will completely delete your Steam history? Is there anything that could completely delete all old logins in accounts banned by VAC-BAN? Or what can you suggest me? My Steam-Guard has been activated; however, since I did not deposit $ 5 to my Steam account, my account is limited and I cannot use the market. I don’t have any other games. I can only play CS:GO and because of the trust factor spinbots and ragebots always come to the opposing team, I have to stay in AFK or leave the game; because there is nothing I can do. I would like to mate with her mother as well, since Valve has not made any explanation for this. It’s a goddamn system.

**Comment by WhatsupDanger** [comment]
formatting the computer won't change anything as steam binds trust factor with HWID so there is nothing we can do. i've seen players with good trust factor and good inventory getting spinnbotters in non-prime only thing i can suggest is to grind and reach level 21. After level 21 you will be promoted to prime which will basically increase your trust factor. i can't say there are no hacker/cheaters in prime but the chances of you getting a spinbot will decrease. there are closet cheaters in prime.

and btw even i have multiple banned accounts on my machine probably 6-7 and 2 of them are overwatch banned (game bans) so whenever i played competitive in matchmaking non-prime i get blatent cheaters but while playing prime i get good players.

out of 10 matches in prime you'll get atleast 3 matches with blatent cheaters, 2-3 matches with smurfs and rest legit players
i can even suggest to avoid solo queue and play with friends who have good trust factors this will slightly reduce the chance of getting a blatent cheater

also remember its not because of your trust factor you're getting spinbotters CSGO JUST HAVE TOO MANY CHEATERS.

**Comment by xpossed-you** [comment]
> We can understand that the confidence factor has decreased with the decrease in gamers looking for games. I am using Vac Bypass Loader. I do not activate Aimbot. I do not activate Wallhack. I am the most legit player in the world, but my trust factor is falling nonetheless. I do not see any decrease in my trust factor when I open a new account and do not inject Osiris. Does using this cheat, first of all injecting it hurts the trust factor?

You are not the legit person if you still inject fam

**Comment by leninismus** [comment]
> > We can understand that the confidence factor has decreased with the decrease in gamers looking for games. I am using Vac Bypass Loader. I do not activate Aimbot. I do not activate Wallhack. I am the most legit player in the world, but my trust factor is falling nonetheless. I do not see any decrease in my trust factor when I open a new account and do not inject Osiris. Does using this cheat, first of all injecting it hurts the trust factor?
> 
> You are not the legit person if you still inject fam

Sorry, what is the “fam” ?

**Comment by WhatsupDanger** [comment]
Let me explain to you what bans means:

VAC ban: it means you used a detected cheat or the current cheat you were using got detected thats why you got a VAC ban

Global Cooldown/Game ban: you were banned by the overwatch system AKA real players which means you're 100% cheating

VACNet: it's an AI system integrated into csgo which detects spinbots and automatically sends them to overwatch not only spinbots it also detects your playstyle and if it finds something fishy it sends you to overwatch (eg aiming players through walls giving perfect headshot to players through smoke everytime etc)

TO counter these bans there are 2 solutions:
1. play legit without any cheats or use faceit
2. to avoid vac ban use vac bypasser loader and to avoid overwatch ban don't use wallhacks or high fov aimbot i.e above 1 fov.

Low trust factor doesn't have anything to do with BANS think of it like this a legit player who has never cheated in CSGO but he's very toxic so people report him for toxic behaviour/abusive comments so his trust factor becomes low over the course of months hence dragging him to red/bad trust factor this would'nt get him a vac ban or game ban so your case your account getting a VAC or Game ban means you did something wrong

how and when to use vac bypasser
vac bypasser is something which makes VAC aborts scan for cheats and at this specific time you inject your cheat so vac thinks you're legit

how to use: make sure steam is not running in background when this condition check run vac bypass loader it should give you your login screen, login and run the game, when CSGO is working i.e started then you must inject your cheat
i suggest you doing this within 3 mins of running vac bypasser because after some time vac starts to scan for cheats again

what not to do with VAC bypasser: i've tried this on multiple accounts that vac bypasser works only once i.e when you run vac bypass and load the game and inject cheat so i highly recommend that when you stop playing csgo exit the steam and do the above process again if you want to play again

run Vac bypasser> login to steam> run CSGO> inject your cheat> 
when done playing or when you quit CSGO and want to play again> repeat all these steps again

also if you're cheating why not use aimbot if you have better aim then dont use i use it on rifles with my fov set to 0.52 and i use recoil crosshair for better recoil control

**Comment by leninismus** [comment]
> Let me explain to you what bans means:
> 
> VAC ban: it means you used a detected cheat or the current cheat you were using got detected thats why you got a VAC ban
> 
> Global Cooldown/Game ban: you were banned by the overwatch system AKA real players which means you're 100% cheating
> 
> VACNet: it's an AI system integrated into csgo which detects spinbots and automatically sends them to overwatch not only spinbots it also detects your playstyle and if it finds something fishy it sends you to overwatch (eg aiming players through walls giving perfect headshot to players through smoke everytime etc)
> 
> TO counter these bans there are 2 solutions:
> 1. play legit without any cheats or use faceit
> 2. to avoid vac ban use vac bypasser loader and to avoid overwatch ban don't use wallhacks or high fov aimbot i.e above 1 fov.
> 
> Low trust factor doesn't have anything to do with BANS think of it like this a legit player who has never cheated in CSGO but he's very toxic so people report him for toxic behaviour/abusive comments so his trust factor becomes low over the course of months hence dragging him to red/bad trust factor this wouldn't get him a vac ban or game ban so in your case your account getting a VAC or Game ban means you did something wrong
> 
> how and when to use vac bypasser
> vac bypasser is something which makes VAC aborts scan for cheats and at this specific time you inject your cheat so vac thinks you're legit
> 
> how to use: make sure steam is not running in background when this condition check run vac bypass loader it should give you your login screen, login and run the game, when CSGO is working i.e started then you must inject your cheat
> i suggest you doing this within 3 mins of running vac bypasser because after some time vac starts to scan for cheats again
> 
> what not to do with VAC bypasser: i've tried this on multiple accounts that vac bypasser works only once i.e when you run vac bypass and load the game and inject cheat so i highly recommend that when you stop playing csgo exit the steam and do the above process again if you want to play again
> 
> run Vac bypasser> login to steam> run CSGO> inject your cheat> 
> when done playing or when you quit CSGO and want to play again> repeat all these steps again
> 
> also if you're cheating why not use aimbot if you have better aim then dont use i use it on rifles with my fov set to 0.52 and i use recoil crosshair for better recoil control.

I understand you very well.

So finally:
Should we trust Krupinski's Vac-Bypass Loader? Or is there a better Vac-Bypass?

There is a lot of talk about CsGhost v4.
Should CsGhost be preferred over Vac-Bypass Loader?

I am grateful for all your valuable explanations.

My aim is very strong, so I never needed an aimbot.

**Comment by WhatsupDanger** [comment]
According to me YES you can trust Daniel's Vac-Bypass Loader and i've never heard of someone else's Vac-Bypass Loader.
CsGhost v4 is used by most of cheaters out there and let me tell you if your injector is detected you might get a VAC ban so i suggest making your own or use this injector created by Daniel himself "https://github.com/danielkrupinski/MemJect" i personally use SAZInjector and i've never used CsGhost 

also there are some videos out there to make the .dll file undetected so i'll list them below

"https://www.youtube.com/watch?v=q1WdXLWa2Wg"
"https://www.youtube.com/watch?v=n73CsyKGf80"

Do remember these doesn't make the dll 100% undetected but the chances of you getting a VAC ban after this would be below 10%
OR you can just google "How to avoid vac ban" & "How to avoid Overwatch ban" those videos could explain you better than me.

**Comment by leninismus** [comment]
> According to me YES you can trust Daniel's Vac-Bypass Loader and i've never heard of someone else's Vac-Bypass Loader.
> CsGhost v4 is used by most of cheaters out there and let me tell you if your injector is detected you might get a VAC ban so i suggest making your own or use this injector created by Daniel himself "https://github.com/danielkrupinski/MemJect" i personally use SAZInjector and i've never used CsGhost 
> 
> also there are some videos out there to make the .dll file undetected so i'll list them below
> 
> "https://www.youtube.com/watch?v=q1WdXLWa2Wg"
> "https://www.youtube.com/watch?v=n73CsyKGf80"
> 
> Do remember these doesn't make the dll 100% undetected but the chances of you getting a VAC ban after this would be below 10%
> OR you can just google "How to avoid vac ban" & "How to avoid Overwatch ban" those videos could explain you better than me.

Thanks for everything. You said the Fov setting is at 0,52... so, what about Smooth? Silent mode active? Are you using Aim assistant at 1? Is it possible that you somehow throw your cfg at me? I would love to examine...

Thank you, again.

**Comment by WhatsupDanger** [comment]
> Thanks for everything. You said the Fov setting is at 0,52... so, what about Smooth? Silent mode active? Are you using Aim assistant at 1? Is it possible that you somehow throw your cfg at me? I would love to examine...
> 
> Thank you, again.

My OSIRIS settings is according to my playstyle so it might be difficult for others to use, but i'll tell you anyways
**AIMBOT**
PISTOLS: all my pistols are set at 0.97 fov NO SILENT and 0 Smoothness i've excluded the CZ75-Auto and R8 Revolver because when you hold your fire button it tracks the player
HEAVY: i don't use aimbot on heavy guns
SMG: i've set all my SMG at 0.52 fov no silent and 0 smoothness
RIFLES: all my rifles are set to 0.52 fov no silent and 0 smoothness, here i've excluded the auto snipers of both teams as it tracks player when we hold the fire button 
Snipers: i'm an AWPer so my awp/scout settings are at 0.97 fov and 1.44 smoothness no silent (it really helps you with your flicks and you sometimes miss some shots which actually looks legit)

**ANTI-AIM/BACKTRACK**
I DON'T USE IT I SUGGEST YOU NOT TO USE IT AS ITS AN HvH (hacker vs hacker) THING.

**TRIGGERBOT**
i use trigger bot only with AWP/SCOUT/ZEUS x27 the reaction time is set to 0ms and i've used ON KEY bind to fire, it really helps with close range noscopes as you just hold the button and flick your mouse and it fires a noscope.

**GLOW/CHAMS**
i've set ON KEY hold for walls i.e when i press X on my keyboard i can see the enemies through walls (i don't use it very much but its handy when you want to win a crucial round)

**VISUALS**
it's personal preference i use it for fps boost i.e no fog no shadow no 3D sky no grass etc i also don't use zoom and thirdperson and bullet tracers. i only use molotov hull

**MISC TAB**
i use auto pistol, auto reload, fast plant, grenade prediction, recoil crosshair, spectator list, etc. and yeah thats it.

i update it from time to time and let me tell you i've been using osiris from march on my one profile and i play with prime players and they've never called me out for cheating. you might be thinking that 0.52 fov with 0 smoothness will track players or flick on their heads, it doesn't .52 helps me with minor recoil control thats it.

You could find my config below but i really thought that you needed an explanation of my cfg DO rate it when you use it
http://www.filedropper.com/casual (after downloading just rename it to casual.dll)

**Comment by WhatsupDanger** [comment]
> My dear brother, thank you very much. You helped me in all matters, you spent your precious time for me.
> 
> I studied your precious CFG. But I suggest you don't be fooled by the fact that your friends are not aware of cheating; When you are going to use an aimbot, give it a button (which you chose f2) and activate aimlock. Just see how you lock on the enemy, how hard it is. **This fov setting is inconvenient,** trust me.
> 
> I want to send you my own settings. I have always faced a Vac ban because I haven't done Vac-Bypass until now. However, in OverWatch, nobody can decide that I am cheating. Because I use neither aimbot nor wallhack.
> 
> But I would like to tell you along with this CFG, the **golden ratio** Fov-Smooth setting I used to use in the past.
> 
> Use my CFG, do the aimbot settings as I say and get used to it. That's when no one will be able to call you cheating.
> 
> I used to play it at **0.62** fov setting. The Fov setting can be adjusted up to **1.02**, but I wouldn't recommend it anyway. The average of 0.62 to 1.02 makes 0.82. **0.81** is preferable for the fov setting (but I was re-averaging 0.62 to 0.81 and was using **0.71**). You have some fov settings that you can choose from 0.62 - 0.71 - 0.81 and 1.02; according to the action of the game you are playing.
> 
> Coming to the Smooth setting:
> 
> **For Pistol:**
> I would prefer _(no silent)_ **15.89**; It can be down to **10.20**. If you wish, you can take an average of these two values ​​and use it. At **0.62 - 0.71 fov setting, 15.89 smooth setting**, even the revolver creates a very sweet impression on the audience and of course the actor, as if it was hit by your own wrist power.
> 
> **For Rifle & SMG:**
> _(no silent)_ Our Fov settings can be preferred as we just mentioned (I was using **0.71**). Our Smooth settings **15,89** are useful.
> 
> **For Sniper:**
> _(yes silent and no scoped only)_ You can make quality AWP - Scout hits with peace of mind at **1.02 fov setting, 10.20 smooth setting.** I did not intervene in it because I did not use AutoSniper. I gave these settings; because not all Aimbots are active in the CFG file I sent. If you want to be active, I definitely recommend that you try what I have said. It will make your wrist feel good and you will never show yourself.
> 
> Against all of your precious statements, I wanted to send you my own CFG. Normally I don't tell anyone about these golden ratio settings, for your information.
> 
> By the way, if you try the aimbot settings on the CFG I sent, you will also need to **activate the aim assistant** (to set it to 1), I set all of them to 0.
> 
> Hopefully it benefits your business:
> 
> https://dosya.co/iksijzxhco7m/M.html

I will try your config later today. like i said this config is according to my playstyle i've spent hours on creating this config and i've already played many competitive matches and reached gold nova 3 without overwatch ban till now and i've watched my own replay at 64 tick and as well as 32 tick and also i've also send my gameplay video to my friends who are gold nova master they think its natural aim. the only reason i use 0.52 fov without smoothness is for recoil control you get on stationary players (eg recoil of ak is downwards and a bit to the left but according to 0.52 fov i just have to pull my mouse downwards and it automatically controls the recoil of first 10 bullets rest is controlled by me with the help of recoil crosshair) and also thanks for that golden ratio info i'll try it in the future
