### ISSUE TITLE
Faceit

### ISSUE THREAD

**Issue by PUREHAX** [danielkrupinski/Osiris#2962]
I was just wondering if is it hard to bypass the Faceit AC ?

**Comment by linuxer9** [comment]
It's hard.
and considering they issue hwid bans it's even harder to evade bans. any public code for bypasser is of course obsolete.
the only thing I see feasible, is hardware cheats, of course no wall hacks or any visuals since the client sends screenshots after each kill, your best bet is cloud radar, RCS and rudimentary triggerbot or mouse event aimbot.
people who cheat in faceit mantain low key, as these cheats are expensive to develop, and they obviously are good players in CS in general so they can hide their cheats better.
or you could easily force cl_junkcode 1.

**Comment by mkot2** [comment]
> or you could easily force cl_junkcode 1.

in that case you also need mouse delta fix patch

**Comment by wemanzoz** [comment]
nah, just add cl_faceitac 1 bypass hook

**Comment by linuxer9** [comment]
> 
> 
> > or you could easily force cl_junkcode 1.
> 
> in that case you also need mouse delta fix patch

yeah, that's right captain
