### ISSUE TITLE
Draw FOV errors

### ISSUE THREAD

**Issue by bhopbhop** [danielkrupinski/Osiris#3126]
hello, ive recently been trying to add a draw fov pull request to osiris. its a bit outdated (https://github.com/danielkrupinski/Osiris/pull/2218) but i have been able to work with it a bit but i think im doing something majorly incorrect. im not the smartest so i had to change a lot because
![image](https://user-images.githubusercontent.com/87729531/126410567-e7d1cb76-df8b-4954-ab12-6bf037ae43d7.png)
 i have almost no idea what im doing
![image](https://user-images.githubusercontent.com/87729531/126410714-1899ecfc-745e-43a7-be6b-68e425a9a62f.png)
![image](https://user-images.githubusercontent.com/87729531/126410724-d4f9bb0e-b8a2-4b42-b7b0-a94cf13a70d9.png)
![image](https://user-images.githubusercontent.com/87729531/126410740-aad86c85-c863-4634-880e-54af3f64a33c.png)

**Comment by impoggin** [comment]
update got everything working except for this error: 
![image](https://user-images.githubusercontent.com/87729531/126413270-da5d4230-c081-49f8-b72e-fa21962f8018.png)

**Comment by impoggin** [comment]
update #2 turns out i was wrong 
Rebuild started...
1>------ Rebuild All started: Project: Osiris, Configuration: Release Win32 ------
1>compilation header save succeeded; see F:\downloads\osiris\Osiris-master\Osiris\Resources\Shaders\Build\default_vs.h
1>pch-c.c
1>pch.cpp
1>Config.cpp
1>ConfigStructs.cpp
1>EventListener.cpp
1>GameData.cpp
1>Aimbot.cpp
1>AntiAim.cpp
1>Backtrack.cpp
1>Chams.cpp
1>EnginePrediction.cpp
1>Glow.cpp
1>Sound.cpp
1>StreamProofESP.cpp
1>Triggerbot.cpp
1>Visuals.cpp
1>Helpers.cpp
1>MinHook.cpp
1>VmtHook.cpp
1>VmtSwap.cpp
1>imguiCustom.cpp
1>imgui_freetype.cpp
1>imgui_stdlib.cpp
1>imgui_tables.cpp
1>InputUtil.cpp
1>Inventory.cpp
1>InventoryChanger.cpp
1>StaticData.cpp
1>ToolUser.cpp
1>Netvars.cpp
1>Osiris.cpp
1>GUI.cpp
1>Misc.cpp
1>Hooks.cpp
1>imgui.cpp
1>imgui_demo.cpp
1>imgui_draw.cpp
1>imgui_impl_dx9.cpp
1>imgui_impl_win32.cpp
1>imgui_widgets.cpp
1>Memory.cpp
1>EconItemView.cpp
1>Entity.cpp
1>GlobalVars.cpp
1>KeyValues.cpp
1>Utils.cpp
1>Texture.cpp
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34,22): error C2011: 'VisualsConfig': 'struct' type redefinition (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(85,53): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(85,68): error C2061: syntax error: identifier 'ColorCorrection' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(87,24): error C2065: 'c': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(87,33): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(88,21): error C2065: 'c': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(88,27): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(89,20): error C2065: 'c': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(89,25): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(90,21): error C2065: 'c': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(90,27): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(91,27): error C2065: 'c': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(91,39): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(92,22): error C2065: 'c': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(92,29): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(93,22): error C2065: 'c': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(93,29): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(94,23): error C2065: 'c': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(94,31): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(97,13): error C2084: function 'void from_json(const json &,BulletTracers &)' already has a body (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(97): message : see previous definition of 'from_json' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(102,13): error C2084: function 'void from_json(const json &,VisualsConfig &)' already has a body (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(102): message : see previous definition of 'from_json' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(104,41): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(104,63): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(105,41): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(105,63): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(106,24): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(106,30): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(107,27): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(107,35): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(108,30): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(108,41): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(109,31): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(109,43): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(110,26): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(110,34): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(111,28): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(111,38): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(112,28): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(112,38): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(113,26): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(113,34): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(114,25): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(114,32): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(115,34): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(115,49): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(116,26): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(116,34): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(117,28): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(117,38): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(118,33): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(118,48): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(119,22): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(119,27): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(120,26): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(120,34): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(121,29): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(121,41): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(122,33): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(122,48): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(123,38): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(123,58): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(124,31): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(124,44): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(125,21): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(125,25): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(126,23): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(126,28): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(127,33): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(127,48): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(128,28): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(128,39): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(129,24): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(129,31): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(130,40): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(130,5): error C2672: 'read': no matching overloaded function found (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(130,46): error C2974: 'read': invalid template argument for 'T', type expected (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\ConfigStructs.h(260): message : see declaration of 'read' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(130,46): error C2780: 'enable_if<!std::is_same_v<T,bool>,void>::type read(const json &,const char *,T &) noexcept': expects 3 arguments - 2 provided (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\ConfigStructs.h(211): message : see declaration of 'read' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(131,38): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(131,5): error C2672: 'read': no matching overloaded function found (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(131,42): error C2974: 'read': invalid template argument for 'T', type expected (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\ConfigStructs.h(260): message : see declaration of 'read' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(131,42): error C2780: 'enable_if<!std::is_same_v<T,bool>,void>::type read(const json &,const char *,T &) noexcept': expects 3 arguments - 2 provided (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\ConfigStructs.h(211): message : see declaration of 'read' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(132,32): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(132,46): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(133,31): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(133,44): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(134,28): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(134,38): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(135,33): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(135,47): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(136,28): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(136,38): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(137,33): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(137,47): error C2661: 'read': no overloaded function takes 2 arguments (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(138,51): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(138,5): error C2672: 'read': no matching overloaded function found (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(138,67): error C2974: 'read': invalid template argument for 'T', type expected (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\ConfigStructs.h(260): message : see declaration of 'read' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(138,67): error C2780: 'enable_if<!std::is_same_v<T,bool>,void>::type read(const json &,const char *,T &) noexcept': expects 3 arguments - 2 provided (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\ConfigStructs.h(211): message : see declaration of 'read' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(139,49): error C2027: use of undefined type 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(34): message : see declaration of 'VisualsConfig' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(139,5): error C2672: 'read': no matching overloaded function found (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(139,63): error C2974: 'read': invalid template argument for 'T', type expected (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\ConfigStructs.h(260): message : see declaration of 'read' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(139,63): error C2780: 'enable_if<!std::is_same_v<T,bool>,void>::type read(const json &,const char *,T &) noexcept': expects 3 arguments - 2 provided (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\ConfigStructs.h(211): message : see declaration of 'read' (compiling source file Hacks\Misc.cpp)
1>F:\downloads\osiris\Osiris-master\Osiris\Hacks\Visuals.cpp(139,63): fatal error C1003: error count exceeds 100; stopping compilation (compiling source file Hacks\Misc.cpp)
1>Done building project "Osiris.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by impoggin** [comment]
yet another update it seems my drawfovcircle does not work for surface

**Comment by demitriusdemarcus** [comment]
Instead of copy pasting everything from that old pull request why don't you read the code, understand what it does and then write it from scratch in your own Osiris? I think that is easier and more efficient

**Comment by linuxer9** [comment]
`void Visuals::drawAimbotFOV(ImDrawList* drawList) noexcept
{
    if (!config->visuals.drawAimbotFOV.enabled)
        return;

    if (!localPlayer || !localPlayer->isAlive()) return;

    const auto activeWeapon = localPlayer->getActiveWeapon();
    if (!activeWeapon || !activeWeapon->clip())
        return;

    auto weaponIndex = getWeaponIndex(activeWeapon->itemDefinitionIndex2());
    if (!weaponIndex)
        return;

    auto weaponClass = getWeaponClass(activeWeapon->itemDefinitionIndex2());
    if (!config->aimbot[weaponIndex].enabled)
        weaponIndex = weaponClass;

    if (!config->aimbot[weaponIndex].enabled)
        weaponIndex = 0;
    const auto& screensize = ImGui::GetIO().DisplaySize;
    float radius = std::tan(degreesToRadians(config->aimbot[weaponIndex].fov) / 2.f) / std::tan(degreesToRadians(localPlayer->isScoped() ? localPlayer->fov() : (105.f + config->visuals.fov)) / 2.f) * screensize.x;
    ImU32 color = Helpers::calculateColor(config->visuals.drawAimbotFOV.color);
    drawList->AddCircleFilled({ screensize.x / 2.0f, screensize.y / 2.0f }, radius, color, 360);
}`
adapt this code to new config system.

**Comment by blackMasterLord** [comment]
#3127
