### ISSUE TITLE
VAC Banned: Security Issue

### ISSUE THREAD

**Issue by SunzBody** [danielkrupinski/Osiris#3149]
Hi, I was recently VAC Banned on CSGO.

I was using Extreme Injector in Manual Map + Stealth Inject, but I kept getting the "Disconnected by VAC" error.
So I decided to use CSGhost 4.2.1 and the next day I got banned.
I would like to know which injector you use, and how do you prevent the risk of ban with Osiris

Thank you very much for your information
Have a nice evening

**Comment by mxez** [comment]
Extreme Injector is detected, don't use it. To prevent the risk of getting banned, we and some of my friends use osiris on Linux.
Never got banned by vac & serverside anti cheat.

**Comment by SunzBody** [comment]
> 
> 
> Extreme Injector is detected, don't use it. To prevent the risk of getting banned, we and some of my friends use osiris on Linux.
> Never got banned by vac & serverside anti cheat.

it seems very interesting thank you for the remark.
With which method (manual map, load library, thread hijacking, simple injection etc..) and if possible which program do you inject the osiris dll?

**Comment by mxez** [comment]
I use GDB tool. All linux internal cheats use this tool to inject their cheat into csgo/tf2/etc. To inject Osiris in one command i use edited cathook's gdb attach script

**Comment by SunzBody** [comment]
if someone has other ideas about Windows, I'm interested too...

**Comment by linuxer9** [comment]
In windows there are 2 detection vectors: the dll itself and the injector

- for injector you can use process hacker 2, it's undetected because it's used for legitimate purposes so I VAC can't ban everyone using it because it's used by legit players. just remember to put the dll in windows folder.
- for the dll, I think it's undetected if you keep updating it everyday when daniel pushes updates, the overall signature is changing keeping it undetected, that's why I think public dll's are not safe, because there's a great chance they are signed by VAC.

also to be completely undetected by VAC, you can use [vac bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader) and use any injector and any dll, it doesn't matter if it's detected or not you won't get vac banned. the only side effect that it can use your trust factor.

**Comment by cheateronly123** [comment]
> In windows there are 2 detection vectors: the dll itself and the injector
> 
> * for injector you can use process hacker 2, it's undetected because it's used for legitimate purposes so I VAC can't ban everyone using it because it's used by legit players. just remember to put the dll in windows folder.
> * for the dll, I think it's undetected if you keep updating it everyday when daniel pushes updates, the overall signature is changing keeping it undetected, that's why I think public dll's are not safe, because there's a great chance they are signed by VAC.
> 
> also to be completely undetected by VAC, you can use [vac bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader) and use any injector and any dll, it doesn't matter if it's detected or not you won't get vac banned. the only side effect that it can lower your trust factor.

Which injector do you recommend?

**Comment by qualk** [comment]
Process Hacker

**Comment by propane** [comment]
@linuxer9 you said that using the vac bypass can lower your trust factor, how so? do you mean because you will be not vac banned and can play more and get more reports or are you saying that server side it detects when vac lacks a heartbeat or something and therefore lowers trust factor? thanks.

**Comment by linuxer9** [comment]
> 
> 
> @linuxer9 you said that using the vac bypass can lower your trust factor, how so? do you mean because you will be not vac banned and can play more and get more reports or are you saying that server side it detects when vac lacks a heartbeat or something and therefore lowers trust factor? thanks.

I don't think my tf is low because of reports, I play legit, only 2 fov aimbot and visible chams, no walls or radar, I even loses most of the time, using vac bypass some how got my account flagged (not banned yet, but it's permenantly on low trust), so I switched to linux and play on another account and everything is fine. I'm really sad about my previous account because of medals, wins and stuff, and even my cheating wasn't worth it.
I don't have a solid mechanism about this, but I suppose valve expect your vac client sends some data back to server, when they recieve nothing for a specific amount of time and this behaviour is repeated, they flag your account.

**Comment by Asviix** [comment]
Use CSGhost for your best chances or never being caught, bypasses VAC and Injects Osiris into Steam perfectly fine, been dropping regular 60k in my games without any bans
