### ISSUE TITLE
aimbot help?

### ISSUE THREAD

**Issue by ma1i1** [danielkrupinski/Osiris#3317]
I don't know if I'm just incompetent or what but id like to know if there's a way to stop this from happening. I have my aimbot fov to 15 and the bone set to nearest 

https://youtu.be/8u97oY8qxe0

**Comment by annpt625** [comment]
@ma1i1 
It shoots the other guy because when you pull the trigger your crosshair is closer to the windows guy. Turn down your FOV and it should be easily fixed.

If you can't do that then just stop legit cheating. Go download some rage cheat and start spinning because 15 FOV is basically just blatant cheating.
