### ISSUE TITLE
[Request] Show damage iwth multi methods.

### ISSUE THREAD

**Issue by Ativ3k** [danielkrupinski/Osiris#3395]
Show damage with multi methods. 

Something like this:  https://forums.alliedmods.net/showthread.php?t=318545

Its possible?

**Comment by mdilai** [comment]
Your link is pointed to a server-side plugin. Its possible to release something similar in Osiris it would be but unnecessary complicated. There is a few similar PRs but i recommend my one - #3399. It show given damage to enemies in ImGUI overlay in same way as spectator and purchase list and show how much HP left. It doesn't show distance because i think it useless in MM.
