### ISSUE TITLE
Welcome Message Box

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#3520]
Hello, some time ago I had created a topic to find the solution to the Message Box and @danielkrupinski  and other people helped me to solve it
https://github.com/danielkrupinski/Osiris/issues/1506

Now I want to place it again and apparently with the changes, this option also changed and it gives me an error again

`class "Interfaces" has no member "gameUI"`

Could you help me?

**Comment by Shuvi-Moro** [comment]
Dude you gave almost zero information what are you waiting for?

**Comment by TauCSGO** [comment]
> Dude you gave almost zero information what are you waiting for?

All the information is in post 1506 as I have quoted
If you don't have text comprehension, please go back to school.
Thanks

**Comment by Ni1kko** [comment]
witch file are you adding it too? does it have the gameUI SDK included?

#include "SDK/GameUI.h"
#include "Interfaces.h"
interfaces->gameUI->createCommandMsgBox("This was a triumph!", "Osiris has been successfully loaded.");

https://github.com/danielkrupinski/Osiris/search?q=interfaces
https://github.com/danielkrupinski/Osiris/search?q=gameUI
https://github.com/danielkrupinski/Osiris/search?q=createCommandMsgBox
https://github.com/danielkrupinski/Osiris/issues/1506#issuecomment-621896836

<3 happy coding

**Comment by mdilai** [comment]
@TauCSGO 
> > Dude you gave almost zero information what are you waiting for?
> 
> All the information is in post 1506 as I have quoted If you don't have text comprehension, please go back to school. Thanks

1) Don't be an asshole. Nobody obligated to help you at all. Here a programmers community, if you are noob you **must** act like a nice guy, be polite and thankful for any help. Or you just will be ignored. Overall, right now you are just lucky that I even spent time for you because I am the last contributor to this functionality and have a time and good mood.
2) Commit 01b55843436bb57440e9b46fe5e61c2cbef17c67 disabled it, and it contains enough info how to re-enable it, if you, to say in your words, went enough to school.

**Comment by TauCSGO** [comment]
> 2. Commit [01b5584](https://github.com/danielkrupinski/Osiris/commit/01b55843436bb57440e9b46fe5e61c2cbef17c67) disabled it, and it contains enough info how to re-enable it.

The only thing I read was the solution, which I appreciate
all the rest is useless
Thanks
