### ISSUE TITLE
ubuntu bad substitution error

### ISSUE THREAD

**Issue by IstAuchEgal** [danielkrupinski/Osiris#3570]
when trying to compile with the command from linux.yml i get this error:
>bash: CMAKE_BUILD_TYPE=${{ matrix.configuration }}: bad substitution

to try to fix it i pasted the command into an script file and made it executable with `chmod +x configure.sh` and then running it with `./configure.sh` and `bash configure.sh` but both didnt work

i also checked other issues and saw #3492 but didnt find anything helpful

**Comment by IstAuchEgal** [comment]
Ah ok I kinda understand now, i change both the `${{ matrix.configuration }}`, but what compile should i use at `${{ matrix.compiler }}`?

**Comment by wumpy2k** [comment]
this should work if you are still trying or someone else has the same problem:

from the beginning:

sudo apt-get update && sudo apt-get install -y libsdl2-dev gcc-10 g++-10

git clone --depth=1 https://github.com/danielkrupinski/Osiris.git
cd Osiris
mkdir Release
cd Release
cmake ..
make -j $(nproc --all)

now you have libOsiris.so, move that to whatever you want and create a file called inject.sh to inject this file to the game

Inject only when you are at the main menu otherwise you may crash!

`
#!/bin/bash

function echo_green {
        echo -e "\\e[32m$*\\e[0m"
}

function echo_orange {
        echo -e "\\e[33m$*\\e[0m"
}

function echo_red {
        echo -e "\\e[31m$*\\e[0m"
}

csgo_pid=$(pidof csgo_linux64)
if [ -z "$csgo_pid" ]; then
    echo_red "CS:GO needs to be open before you can inject, exiting..."
    exit 1
fi

filename="libOsiris.so"

# Credit: Aixxe @ aixxe.net
if grep -q "$filename" /proc/"$csgo_pid"/maps; then
    echo_orange "Osiris is already injected, aborting..."
    exit
fi

sudo cp "$filename" "/home/$USER/${filename}"

killall -19 steam

input="$(
sudo gdb -n -q -batch-silent \
        -ex "set logging file /dev/null" \
        -ex "set logging redirect on" \
        -ex "set logging on" \
        -ex "attach $csgo_pid" \
        -ex "call ((void*(*)(const char*, int))dlopen)(\"/usr/lib/$filename\", 1)"   \
        -ex "detach" \
        -ex "quit"
)"

killall -18 steam

rm "/home/$USER/${filename}"

echo_green "Successfully injected!"
`

**Comment by IstAuchEgal** [comment]
omg thank you it worked although i had to install freetype first 

for anyone having the same problem just install the `libfreetype6-dev` package
