### ISSUE TITLE
My fps dropps from 500 to 180's in dust 2

### ISSUE THREAD

**Issue by YiitCan** [danielkrupinski/Osiris#3757]
I don't know how you managed to make a 3080 give 180 fps in a 2012 game just by a single dll file but. please fix it in the fastest way possible.

**Comment by stressatoo** [comment]
You said right, the game engine is 10 years old, hence why it's not optimized like the most recent ones.
Try to remove some options such as overlays, ESPs, lowering FOV.

**Comment by Xsintashi** [comment]
weird i have same fps than without lol

**Comment by n4vi98** [comment]
make sure when u compiled the dll select release x86 if its debug your fps will suffer

**Comment by ByMynix** [comment]
FPS drops are normal with cheats, but not that high. Try changing the CPU optimisations for Osiris, because it's not the GPU in connection with Osiris. Quote from danielkrupinski in the description of Osiris: 

"If your CPU supports AVX / AVX2 / AVX-512 instruction set, you can enable it in project settings. This should result in more performant code, optimized for your CPU. Currently SSE2 instructions are selected in project settings."

That could fix the problem, or rather make it more bearable.
