### ISSUE TITLE
update on cs2?

### ISSUE THREAD

**Issue by NGGYOK** [danielkrupinski/Osiris#4135]
have a plan to update Osiris be working on cs2?

**Comment by Keffori** [comment]
I want cs2 Osiris too

**Comment by zikehalil3535** [comment]
14.09.2023 still waiting

**Comment by Valeedb** [comment]
Prob not

**Comment by fanat1cc** [comment]
You can try and start porting it over using:
https://cstrike2.oof.lv/index.php?forums/oof-lv-client-news-download.2/
From what I have hurd cs2 porting is more simple than expected however injection might need to be kernal driver mapping or kernal manual map instead of load library. @danielkrupinski this may help you as well
