### ISSUE TITLE
CSGO crashes on injection Ubuntu 22.04 on Parallels VM.

### ISSUE THREAD

**Issue by zachtie** [danielkrupinski/Osiris#4136]
Just as said. I got the latest source, built with cmake on vscode and on injection it crashes CSGO. I will further test.

**Comment by zachtie** [comment]
Ok So newest release of source crashes csgo on ubuntu regardless of VM type.

**Comment by hamad12a** [comment]
@danielkrupinski Could you "address" hints on how you find new patterns after the game gets updated?
Using the GDB debugger I don't know where to put the breakpoint(s) to display the corresponding pattern address.
Because I am struggling after each game update the same issue is being created again and again!

**Comment by danielkrupinski** [comment]
Fixed
