### ISSUE TITLE
Point the haircut indicator towards the head

### ISSUE THREAD

**Issue by MaYecha** [danielkrupinski/Osiris#4315]
Point the haircut indicator towards the head
It's difficult to align with the explosion line when placed at the bottom
I tried to modify it but failed
ths

**Comment by freebritney132** [comment]
It would be better to just add proper boxes or skeleton rendering. I tried to, but I can't even figure out how to get the struct for bones because I don't know where to get these memory patterns https://github.com/danielkrupinski/Osiris/blob/master/Source/MemoryPatterns/Linux/EntityPatternsLinux.h and drawing lines with panorama seems complicated.

**Comment by danielkrupinski** [comment]
Recently "Player outline glow" was added which should fix the issue:
![player color glow](https://github.com/user-attachments/assets/c396147b-7943-4a27-8878-1efa3c64be62)
