### ISSUE TITLE
Game still crash

### ISSUE THREAD

**Issue by Shiv3RPolak** [danielkrupinski/Osiris#433]
game still crash with same error as in #415. THIS IS VERY ANNOYING.

**Comment by 0xE232FE** [comment]
I remember I had this error once in one Matchmaking Session. I thought it was Steam related, because I found the "CUtIRBTree Overflow Error" on several Posts on Bulletineboards. During the Match i was Removing the Visual Studio 2017 installation and I was installing Visual Studio 2019, which produced a high CPU Load during its installation. Even my Core i9 9900K got hot work and stuttering even with GTX 1080 Ti. CSGO got slow during installation process, fuck off Single Threadding 32 bit csgo.exe. Fucking legecy Game XD

**Comment by Shiv3RPolak** [comment]
Its because old config, did new and 0 crashes.
