### ISSUE TITLE
Fake Ban color not working? 

### ISSUE THREAD

**Issue by Evilhelder** [danielkrupinski/Osiris#533]
![image](https://user-images.githubusercontent.com/33970481/64996161-9a3dd580-d8b3-11e9-9eee-8a1915eb66fb.png)
![image](https://user-images.githubusercontent.com/33970481/64996178-a033b680-d8b3-11e9-9ce3-2a8d8d2dfc8d.png)

Isn't it working or did I do something wrong?

**Comment by Evilhelder** [comment]
now it works.... it only works if I turn on Custom Clan ...

![image](https://user-images.githubusercontent.com/33970481/64996613-c3ab3100-d8b4-11e9-864d-e296d21c38dc.png)

**Comment by yumyumrice** [comment]
Samething here. I think that the white color is client sided, because in misc.cpp the color is set /x01 (white) and it looks as if the server sees red (without clantag) but you do not. I am not sure, that this is true, but maybe if you set the color to /x07 (red) it may work. I have not tried, but will and update this response.

**Comment by yumyumrice** [comment]
So this only does work with a clantag, and it is both server and client sided. Changing the color value to /x07 does not work. Maybe change your clantag to [Server]? Im not sure, but until it is fixed, i would do that

**Comment by deXyy999** [comment]
so many things in osiris are so badly programmed that it hurts
