### ISSUE TITLE
{improvement}

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#541]
hello, this is a list of things you should improve:
RCS(be able to make it more blatant or legit at will)
The RCS is way too legit, I think you should rework it so that it can be as legit as possible (like now)
or as obvious as possible (rage RCS) or between both.
The aimbot is ok but I'm thinking, instead of using typical smooth, why not use speed p/y?
that would improve it by a lot IMO, also, why not add response time to the aimbot 
because it switches targets too quick so it's very blatant sometimes
also make it so that we can edit the RCS's smooth because I have a very legit setting so the RCS uses the aimbot's smooth which is bad can you change that(this is mostly optional )(I can't add any of these myself since I have no coding experience

**Comment by VuBrian22** [comment]
As of right now, the cheat has mostly Aim RCS. Complete Standalone RCS is what you're looking for here. Some cheat (I don't remember) had both Standalone RCS and Aim RCS and it works as expected. one can be very blatant and the other is super legit, of course this also is a variability due to the slider to change the RCS x and y values. And even though if you use speed smooth than it would look a lot more obvious as it normally would. Regular smooth is fine, but you can turn up the max aim values to get the full potential. You can just paste your own modified RCS if you're comfortable with that. I would help as best as I can as to making a pull request and changing it myself and getting it approved, however I have school with 5 exams this coming Friday. I hope my opinion helps.

**Comment by HowToMakeFaceitAB** [comment]
thank you very much
I use onetap for blatant cheating, I realized their RCS is amazing and good,
their speed is also amazing and good. I just thought that it might be a good idea,
I don't know how to add anything to a cheat to be honest with you.

**Comment by HowToMakeFaceitAB** [comment]
I don't know how to remove functions or even add them.

**Comment by anonymouschicken111** [comment]
So you want a function you can copy paste or you just want this feature to be added to Osiris?

**Comment by deXyy999** [comment]
nope, the cheat itself has AWFUL aim rcs.. u cnt recognise it :)) also, the glow occluded is awful, not working :))

**Comment by HowToMakeFaceitAB** [comment]
The health esp is trash

**Comment by VuBrian22** [comment]
> nope, the cheat itself has AWFUL aim rcs.. u cnt recognise it :)) also, the glow occluded is awful, not working :))

The cheat was made for super legit cases and currently doesn't support semi-rage or rage-settings.

**Comment by deXyy999** [comment]
u don't say lol it's paste tho

**Comment by hydemods** [comment]
> u don't say lol it's paste tho

And it's open source so you can fix it yourself :))

**Comment by LuanGraa** [comment]
any good gentlemen here to fix the offsets that valve patched?

**Comment by deXyy999** [comment]
> > u don't say lol it's paste tho
> 
> And it's open source so you can fix it yourself :))

Exactly

**Comment by HowToMakeFaceitAB** [comment]
I realized why the aim rcs was so trash
It was because i was trying to control the recoil myself which ended up messing up the rcs. To fix that i use triggerbot for long range foghts and aimbot for close and medium rage

**Comment by deXyy999** [comment]
guys also while i inject, its ok, but when i join community server, game crashes.. is it something with the new update??

**Comment by VuBrian22** [comment]
> guys also while i inject, its ok, but when i join community server, game crashes.. is it something with the new update??

Cheat was just updated. Try recompiling and injecting again, If all else fails, the problem lies in your injector.

**Comment by deXyy999** [comment]
Fixed it, fucked up code
