### ISSUE TITLE
Reportbot question

### ISSUE THREAD

**Issue by RadicalRedemption** [danielkrupinski/Osiris#545]
I see the reportbot submits a single report for each player on the team you have selected. When i submit reports manually, i have noticed that every report has a different ID, which means that every report you submit for a single player counts. Do you think if the reportbot doesn't stop reporting the enemy players at the selcted period, could get you banned? If it just keeps spamming reports every 10/15 seconds.

**Comment by 0xE232FE** [comment]
If you spam Reports this might have consequences on your Trustfactor. I never report people I am not sure. After watching the Demo and find someone is convicted for cheating, I try to make friend with him and play a game on casual and report him there with my report bot. Because Reportbots need [SERVER_ID] and have to login on same server with the suspect.

The Reportbot implemented in Osiris is just a ingame auto report system. I use 500 Free CSGO Accounts on my nodeJS Reporting bot. Besides the commend bot works same today you can commend even with free accounts. Only thing is you need to be on same server with the guy you want to commend or report.

**Comment by RadicalRedemption** [comment]
> 
> 
> If you spam Reports this might have consequences on your Trustfactor. I never report people I am not sure. After watching the Demo and find someone is convicted for cheating, I try to make friend with him and play a game on casual and report him there with my report bot. Because Reportbots need [SERVER_ID] and have to login on same server with the suspect.
> 
> The Reportbot implemented in Osiris is just a ingame auto report system. I use 500 Free CSGO Accounts on my nodeJS Reporting bot. Besides the commend bot works same today you can commend even with free accounts. Only thing is you need to be on same server with the guy you want to commend or report.

So, the reportbot in Osiris is kinda pointless?

**Comment by HowToMakeFaceitAB** [comment]
Pretry much

**Comment by danielkrupinski** [comment]
It does essentially the same as reporting player in scoreboard, but automatically.
