### ISSUE TITLE
[Suggestion]Aimbot switch delay

### ISSUE THREAD

**Issue by Ebzdyberybencjusz** [danielkrupinski/Osiris#571]
Hi, i think the option for aimbot target switch delay would be very useful.

**Comment by hyperxpro** [comment]
It doesn't make Aimbot have a delay. Better use Trigger Bot.

**Comment by VuBrian22** [comment]
Honestly, I don't even use aimbot at all, well maybe some with a smooth of 1.67 and 100 x & y RCS. And finally TriggerBot with all weapons with 32ms of delay. This should look legit almost all the time. No need for Aimbot Delay.....TriggerBot does most of the heavy lifting.

**Comment by Ebzdyberybencjusz** [comment]
Its not aimbot delay but target switch delay when in crosshair are 2 targets

**Comment by VuBrian22** [comment]
If that's the case, then well, in my opinion that wouldn't be necessary. Although if you are just bad at the game and not learn how to spray then oh well, sure I agree. However in my case, I don't mind because the aimbot in Osiris is for super legit plays only and the most I use is triggerbot with a delay. Alternatively however you can tweak the aimbot to work on a key, so when two targets are close, all you do is hit that key and it aims for the target closest, kills that target, and will "smooth" aim to the next person.

**Comment by Asviix** [comment]
@Ebzdyberybencjusz Sorry to revive an old Issue, I will look into it and will keep you updated if I can make it
