### ISSUE TITLE
{Suggestion} Anti OBS

### ISSUE THREAD

**Issue by XkamiXYT** [danielkrupinski/Osiris#572]
simple anti obs

**Comment by VuBrian22** [comment]
It would be nice to have this in the cheat. You can just paste it from another cheat if you want. I just found an Indigo Paste with an OBS Hider and pasted that into my copy of Osiris and compiled it.

**Comment by RadicalRedemption** [comment]
> 
> 
> It would be nice to have this, officially, in the cheat. You can just paste it from another cheat if you want. I just found an Indigo Paste with an OBS Hider and pasted that into my copy of Osiris and compiled it , although I had to tweak some stuff because some elements of the cheat were still visible in OBS Recordings and Streams.

Can you share your source with us?

**Comment by neazen** [comment]
Yeah would be nice, btw i think it was rendering esp's in endscene smthing like that

**Comment by 0xE232FE** [comment]
this should work on any game with the steam overlay
obs (and most recording software i know) hook endscene via the d3ddevice ptr and filter calls so they wont capture anything when its called from gameoverlay (or anywhere else)

this is more reliable than hooking present since if you open obs after injecting your cheat or obs decides to re-hook your visuals will show up

requires you to have "capture game overlays" disabled

in endscene:
```
    	static uintptr_t gameoverlay_return_address = 0;
     
    	if( !gameoverlay_return_address ) {
    		MEMORY_BASIC_INFORMATION info;
    		VirtualQuery( _ReturnAddress( ), &info, sizeof( MEMORY_BASIC_INFORMATION ) );
     
    		char mod[ MAX_PATH ];
    		GetModuleFileNameA( ( HMODULE )info.AllocationBase, mod, MAX_PATH );
     
    		if( strstr( mod, xors( "gameoverlay" ) ) )
    			gameoverlay_return_address = ( uintptr_t )( _ReturnAddress( ) );
    	}
     
    	if( gameoverlay_return_address != ( uintptr_t )( _ReturnAddress( ) ) && g_settings.misc.hide_from_obs ) 
    		return end_scene_o( device );
```

source: https://www.unknowncheats.me/forum/counterstrike-global-offensive/276438-stream-proof-visuals-method.html

**Comment by danielkrupinski** [comment]
Stream Proof ESP has been added.
