### ISSUE TITLE
Veiled injector

### ISSUE THREAD

**Issue by 1-Xycro** [danielkrupinski/Osiris#608]
Is veiled injector safe?

**Comment by neazen** [comment]
A lot of people uses it, I don't know if it's safe but I'd suggest you to use https://github.com/bananasss00/Rando-Injector, add junk code, and if you want to be more safe vmp it and ur good to go.

**Comment by Arkadio918** [comment]
proces hacker ez injector from

**Comment by RadicalRedemption** [comment]
I use my own injector, that uses "Reflective DLL Inection" technique, which includes manual mapping. It's pretty safe and stable. Custom injectors are always safer.

**Comment by 0xE232FE** [comment]
Seriously you even believe that  __asm_emit__ is protecting you from VAC Signature scans? Guys please be professional this isn't true and you know it! Remove all the Random stuff in Rando injector and see that it isn't detected!!!

**Comment by deprale** [comment]
> A lot of people uses it, I don't know if it's safe but I'd suggest you to use https://github.com/bananasss00/Rando-Injector, add junk code, and if you want to be more safe vmp it and ur good to go.
> Been using it for a long time without problem. :d

I don't understand how junk code is gonna protect anything, if anything vmp is only making your signature unique and mutates your code, the cheat itself is still detected you're only evading signature scanning...
Therefore the junk code is USELESS. Let's not forget that most of you that use junk code don't even know how to VMP a .DLL properly.
If an injector is detected, no amount of junkcode is gonna save you from a VAC or UNTRUSTED ban lol, cause the core code is the same. VAC detects only a few injection techniques as the people don't want it to be "invasive", and LoadLibrary/A is one of them, because a lot of legit modules inject themselves in other processes like that.

**Comment by furioushell98** [comment]
@deprale honestly idk much about detection and stuff but i don't think he means using these auto junk code adders by" adding junk code". When you compile Randoinjector you have a bunch of bytes to change in order to make a different copy of Randoinjector. I used this injector for weeks on nonprime, never got untrusted/vac on my accounts. Also if you think it is detected what do you recommend then?

**Comment by Kraken69** [comment]
is there any injector i can use without adding junk codes and other things without getting banned?

**Comment by 0xE232FE** [comment]
The most difficulty in LoadLibrary is to find LoadLibrary in KERNL32 because of Address Randomization. Any LoadLibrary injector is working and is always undetected if you code it yourself.
