### ISSUE TITLE
{suggestion} doorspam like in skeet

### ISSUE THREAD

**Issue by ccsimplyspolit** [danielkrupinski/Osiris#619]
add doorspam feature
doorspam.cpp
```#include "doorspam.h"

#include "../settings.h"
#include "../interfaces.h"

bool Settings::DoorSpam::enabled = false;
static bool ShouldSpamDoors = false;

void DoorSpam::CreateMove(CUserCmd* cmd)
{
	if (!Settings::DoorSpam::enabled)
		return;

	C_BasePlayer* localplayer = (C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer());
	if (!localplayer)
		return;

	if (cmd->buttons & IN_USE){	

		for (int i = 1; i < entityList->GetHighestEntityIndex(); i++)
		{			
			C_BaseEntity* entity = entityList->GetClientEntity(i);
			if (!entity)
				continue;

			ClientClass* client = entity->GetClientClass();

			if (client->m_ClassID == EClassIds::CPropDoorRotating){
				if (localplayer->GetVecOrigin().DistTo(entity->GetVecOrigin()) < 100){
					if (ShouldSpamDoors){
						cmd->buttons &= ~IN_USE;
					} else {
						cmd->buttons |= IN_USE;				
					}
					ShouldSpamDoors = !ShouldSpamDoors;	
				}
			}
		}

	}
}
```

doorspam.h
```
#pragma once

#include "../SDK/IInputSystem.h"

namespace DoorSpam
{
	//Hooks
	void CreateMove(CUserCmd* cmd);
}
```

imgui
```
ImGui::Checkbox(XORSTR("Door Spam"), &Settings::DoorSpam::enabled);
```

**Comment by anonymouschicken111** [comment]
You forgot Hooks.cpp and Config.h and Config.cpp
It's not ImGui it's GUI.cpp
It's not `CUserCmd*` cmd it's `UserCmd* cmd` (btw you can drop the cmd in the header file)
Osiris ain't got em' classes
`C_BaseEntity`
`ClientClass`

The config system's different
configs.doorSpam.enabled
Since you said door spam you have to add a struct named doorSpam in Config.h with a
`bool enabled{ true };`

In the head file it's
`#include "../SDK/InputSystem.h"`

Then you have to add it to Hooks.cpp

And also how the hell is doorSpam useful, I'm pretty sure Osiris is a legit cheat and you'd probably get vacced when use this cheat without junkcode and shit.

**Comment by 0xE232FE** [comment]
Copy & Paste from Aimtux doesn't help here dude.
