### ISSUE TITLE
Crash in loading screen,

### ISSUE THREAD

**Issue by milxn** [danielkrupinski/Osiris#632]
Someone know how to fix cheat after cs update? After inject when i wanna play in loading screen game crash. Offsets or something?

**Comment by anonymouschicken111** [comment]
Yes most updates offsets change

**Comment by milxn** [comment]
Where i can found a new offsets? Im newcommer at pasting ;/   Yes most updates offsets change —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

**Comment by anonymouschicken111** [comment]
Woah calm down, the author is most inactive but I can imagine him read these threads and think about how autistic people can be

**Comment by Bywnb** [comment]
Everything is ok, the game did not happen

**Comment by VuBrian22** [comment]
After the update yesterday, depending on where you live, the offsets had not changed. Just recompile  the source and inject the dll again. It shouldn't crash. And also since Osiris uses an interface changing the offsets aren't that simple. Check here to find out more: https://github.com/danielkrupinski/Osiris/issues/542 Also Check here to find out the same method on finding those irregular offsets: https://github.com/danielkrupinski/Osiris/pull/583

**Comment by danielkrupinski** [comment]
I've tested on official and community servers and everything works fine.

**Comment by anonymouschicken111** [comment]
@danielkrupinski yeey u alive
