### ISSUE TITLE
[Visuals] Changing resolution

### ISSUE THREAD

**Issue by HyeN2018** [danielkrupinski/Osiris#664]
If i inject the cheat first and than i change my resolution from 16:9 to 4:3 all texts including Bomb timer , esp names , watermark are bigger than normal .
If i inject the cheat after changeing the resolution everything is normal.

**Comment by sundafused** [comment]
then don't change resolution? It's not really an issue, I've noticed the same thing.

**Comment by VuBrian22** [comment]
Once the cheat is injected into the game, it remembers your current resolution and sticks with it until you quit the game or unhook the cheat. That's why when you change your aspect ratio, all the cheat remembers is that the game is in 16:9. Therefore all the cheat's GUI and HUD assets are scaled at 16:9 and not 4:3.

**Comment by anonymouschicken111** [comment]
Dumbass

**Comment by thomas0aotian** [comment]
bruh there is an console command

**Comment by CallieOwO** [comment]
There are ways of fixing this by checking with screensize is changed and reinitializing everything but I don't think it'd be the most reliable way.
