### ISSUE TITLE
How to get info about current match?

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#781]
Is it have a way to get info about current match?

**Comment by tirziz** [comment]
what kind of info do you need ?

**Comment by thomas0aotian** [comment]
Rly can't help

**Comment by NexSqaud** [comment]
@tirziz Map, gamemode, phase, team scores

**Comment by rosesware** [comment]
you open cs:go and see, wtf!

**Comment by tirziz** [comment]
Check CSPlayerResource maybe, I don't often mess around with that

**Comment by 0xE232FE** [comment]
You can query the WebAPI for current match info. Even if the Player has private Profile! I use this API to get Info of players that I in Reportbot Queue and if they join a casual match I can Reportbot them to lower their Trustfactor.
Keep in mind Report and Commend Bot still working but only if you have Serverid and you can join the same server. You can still do anything over the WebAPI.
For Matchmaking you get the Serverid but you can not join the Server because it is Password protected the Reportbot can not report players in Matchmaking anymore. But in causal matches!

**Comment by AbdallahMehiz** [comment]
wtf do u mean by info of current match man
u have the scoreboard :/

**Comment by thomas0aotian** [comment]
@AbdallahMehiz kid we are talking about coding stuff here stay away if you don't know nothing
