### ISSUE TITLE
organize skinchanger

### ISSUE THREAD

**Issue by Laxybaxy** [danielkrupinski/Osiris#782]
make the skinchanger so it shows just skins for the selected weapon. its takes a lot of time to setup skins.

**Comment by thomas0aotian** [comment]
Duplicate #728

**Comment by cojo1989** [comment]
Daniel will not do that. I don`t know why, ask him

**Comment by thomas0aotian** [comment]
I found a old thread about this which might help. #296

**Comment by cojo1989** [comment]
Daniel will not do that... he does not want it. :)

**Comment by thomas0aotian** [comment]
@cojo1989 he got his own business going on here and idt he owe u anything. This source is completely free and opened, what's the point of begging danial for doing things that u wanted to without urself even trying to make it. An open source project allowed ppl to gather together and make this project better instead of fking ASKing Daniel to do stuff for u this is ISSUES TAB this ain't no fucking SUPPORT TICKET.

**Comment by cojo1989** [comment]
> @cojo1989 he got his own business going on here and idt he owe u anything. This source is completely free and opened, what's the point of begging danial for doing things that u wanted to without urself even trying to make it. An open source project allowed ppl to gather together and make this project better instead of fking ASKing Daniel to do stuff for u this is ISSUES TAB this ain't no fucking SUPPORT TICKET.

Do you saw me begging? Did you saw me ask Daniel for something beside old issues? I was just answer to the owner ticket. So please be carefull to who you reply. Thank you bro.

**Comment by danielkrupinski** [comment]
Now you can search skins for certain weapon.
