### ISSUE TITLE
Detected

### ISSUE THREAD

**Issue by shadowkiller990** [danielkrupinski/Osiris#852]
I got Detected, but it was a warning to remove any software modifying my skins or textures, something along those lines, after I removed the software, repaired, cs go I was able to play again

**Comment by agshaidun** [comment]
i got this too

Disconnected by VAC: You cannot play on secure servers

Modifying game files and/or in-game textures may cause this error.
 
Please remove any custom textures, skin changers, or software that modifies game files and restart your computer. We also recommend verifying your game files after making these changes.

**Comment by thomas0aotian** [comment]
@agshaidun u prob use the onetap.crack so u got these. U changed the depot

**Comment by agshaidun** [comment]
> 
> 
> @agshaidun u prob use the onetap.crack so u got these. U changed the depot

omg you were right

**Comment by agshaidun** [comment]
> 
> 
> @agshaidun u prob use the onetap.crack so u got these. U changed the depot

how do i change the depot back ??

**Comment by thomas0aotian** [comment]
Just verify ur game's integrity

**Comment by rosesware** [comment]
Use @danielkrupinski [VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader).

**Comment by PostmanTap** [comment]
dont use antiaim or rage aimbot over 40fov and u wont get vac kick, if u do get vac kick just change account / sign out and back in and wait for like 10-20 mins

**Comment by travispresk0** [comment]
This is because of nSkinz. Been using nSkinz (by namazso) and after atleast 5 rounds I get VAC kicked

**Comment by anonymouschicken1111** [comment]
I mean what did you expect?

**Comment by littlehurensohn** [comment]
Cheat ain't detected, if your newcomer and don't know how to protect cheat from vac don't paste. 
Only maximally for us what have some knowledge, is possible vac error. 
Close this issue, and dont have more dumb questions.

**Comment by xAkiraMiura** [comment]
# VAC.NET, not VAC

the reason you are betting VAC Auths is because you are playing blatantly. if you understand vac banning patterns (if your ban takes a certain time to escalate to a vac ban then you can determine if it was VAC.NET or VAC) you will see that your ban is because of VAC.NET, not VAC. the cheat is not detected (my accounts have lasted for weeks while using the cheat unmodified).
be mature and stop raging. then your accounts wont get vac authed instantly.

about skins, valve will vac auth you for skin changers however i don't think nSkins is authed. i play with the skin changer for every skin and i dont get vac authed until i start raging

use max angle delta if you really are too immature to aimbot so often.
