### ISSUE TITLE
Rage test

### ISSUE THREAD

**Issue by agshaidun** [danielkrupinski/Osiris#898]
Not bad :D
Autowall
AutoScope
AutoShoot 
all perfectly working fine . You just need to adjust the setting

https://www.youtube.com/watch?v=vH3SpKaM-4c

**Comment by num3rical** [comment]
That's a really good config. For some reason the AA never actually works for me and I always end up shooting the ground, did you do anything special to fix it?

**Comment by agshaidun** [comment]
I'm just copying everything from here
#739
I didn't do any modification 🤔

**Comment by AbdallahMehiz** [comment]
> Not bad :D
> Autowall
> AutoScope
> AutoShoot
> all perfectly working fine . You just need to adjust the setting
> 
> https://www.youtube.com/watch?v=vH3SpKaM-4c

can you try it on an hvh sever or in mm hvh

**Comment by MinecraftGoodGame** [comment]
Osiris doesn't do well vs spinners probably because it doesn't have a resolver

**Comment by arkx3** [comment]
> 
> 
> Osiris doesn't do well vs spinners probably because it doesn't have a resolver

it doesn't have multipoint, nor resolver
I could often hit head but I were still getting body aimed cuz I couldnt hit someone's body/head due to lack of multipoint

**Comment by agshaidun** [comment]
> 
> 
> > Not bad :D
> > Autowall
> > AutoScope
> > AutoShoot
> > all perfectly working fine . You just need to adjust the setting
> > https://www.youtube.com/watch?v=vH3SpKaM-4c
> 
> can you try it on an hvh sever or in mm hvh

already did . i can tap other paste cheat but not premium cheat

**Comment by agshaidun** [comment]
> 
> 
> > Osiris doesn't do well vs spinners probably because it doesn't have a resolver
> 
> it doesn't have multipoint, nor resolver
> I could often hit head but I were still getting body aimed cuz I couldnt hit someone's body/head due to lack of multipoint

also the engine prediction need to be improve too . sometimes i miss shot even on nospread

**Comment by PostmanTap** [comment]
> > > Osiris doesn't do well vs spinners probably because it doesn't have a resolver
> > 
> > 
> > it doesn't have multipoint, nor resolver
> > I could often hit head but I were still getting body aimed cuz I couldnt hit someone's body/head due to lack of multipoint
> 
> also the engine prediction need to be improve too . sometimes i miss shot even on nospread

there is no engine prediction...

**Comment by AbdallahMehiz** [comment]
i tried it on an hvh server, it does pretty well for a free open source cheat.
the problem is that it targets fakes, and have a problem shotting reals. it needs a resolver.
the other problem is that then anti aim is easy to counter for the other cheats. anti-aim needs to be improved. and it misses shots quite often.

**Comment by rosesware** [comment]
> i tried it on an hvh server, it does pretty well for a free open source cheat.
the problem is that it targets fakes, and have a problem shotting reals. it needs a resolver.
the other problem is that then anti aim is easy to counter for the other cheats. anti-aim needs to be improved. and it misses shots quite often.

The "founder" of Anti aim pull request get away of cheats and course cheating. He also promise put an a resolver in December (this month) but well, he quit of cheating.
