### ISSUE TITLE
I need quality legit config

### ISSUE THREAD

**Issue by furkansrby** [danielkrupinski/Osiris#903]
Hello to everyone. Do you have a quality legit config that you use?

**Comment by MinecraftGoodGame** [comment]
It's a personal preference, I'd recommend making one yourself.

**Comment by furkansrby** [comment]
yes ı know but I want to use different people's settings

**Comment by VuBrian22** [comment]
@furkansrby Here is my config. If its good or decent enough please let me know. I'll try to improve mine. https://anonfile.com/33m8d2I5n9/Legit_V1-Brian_Vu

**Comment by linkupbiz** [comment]
depends on rank really.
silver to gnm: use about 5 fov with 10-15 smoothing, about 60 x and 70 y rcs, aimlock, closest bone.
mg-dmg: use 1-2 fov with 3-4 smothing, about 80-90 x and y rcs, aimlock, target neck, chest, or head (pref chest).
le-ge: use 1-2 fov with 2 smoothing, 90 x and y rcs, aimlock, target neck or head.

reasoning: 
on lower ranks people tend to just rush out on to sites or basically anywhere together, you don't want your low smoothing and high fov to just lock on to peoples bodies.

on higher ranks people tend to make strategic moves, such as sending a single person a, or baiting teammates on to sites which makes a small fov and low smoothing perfect because it will just appear as a small flick, which for a higher rank player is not hard to do.

**Comment by VuBrian22** [comment]
@linkupbiz True.

**Comment by travispresk0** [comment]
what does aim lock actually do?

**Comment by tirziz** [comment]
My legit config:
+ RCS x : 85 / RCS y : 0.
+ Visible charm only.
+ ESP Weapons < 25 meters away.
+ Bomb timer.

**Comment by AbdallahMehiz** [comment]
i actually dont use aimbot on my legit ._.

**Comment by Sapphire1337420** [comment]
https://www.mediafire.com/file/dx3ytmp0s2avqcq/Prime/file

**Comment by craxking** [comment]
thanks for the cool cfgs guys :)

**Comment by DokanBoy** [comment]
Somebody have a "rage" config?

**Comment by nucreac** [comment]
https://drive.google.com/open?id=1FWB7zA8R-eMW2Z_AX6j10Je54OqgPiUb

Maybe not the best legit config, no aimbot, but hey, at least it's there. Been using this config for quite a while. I'd say 2 months.
