### ISSUE TITLE
[SUGGESTION] add sv_pure bypass cuz i am 2 retarded to add it myself

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#947]
Well, everyone likes old gloves, old sounds, maybe even custom models
so please do add that bypass k thanks

**Comment by 8cy** [comment]
"i'll just preface this by saying that there are probably a bunch of other ways to bypass sv_pure, this is just one I found by "accident" when logging messages getting sent through SendNetMsg a while back. regardless of this I don't see any point in bypassing it, but since there was a post yesterday asking for it I thought I might aswell just post an easy way to do it on the off chance that someone wants/needs it. 
changing models/whatever in the game files with this obviously works, but please don't do it since its ghetto asf.

aight first of all, setup your SendNetMsg hook, and remember you have to rehook it everytime it gets reallocted and pointer changes (happens on mapchange etc), simply check that pointer is valid and if it changed since hooking it you hook/rehook it wherever you like, cm, fsn, whatever.

in the hook itself simply check the message for type 14 and return so it doesnt send the FileCRCCheck message:

Code:

```
bool __fastcall Hooks::SendNetMsg(INetChannel* pNetChan, void* edx, INetMessage& msg, bool bForceReliable, bool bVoice)
{
    if (msg.GetType() == 14) // return and don't send messsage if its FileCRCCheck
        return false;
 
    if (msg.GetGroup() == 9) // fix lag when transmitting voice and fakelagging
        bVoice = true;
 
    return g_Hooks.oSendNetMsg(pNetChan, msg, bForceReliable, bVoice);
}

```
for some reason servers don't care if they don't get any FileCRCCheck messages at all, ohwell.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xAkiraMiura** [comment]
you can hook FindMDL (ghetto)
or you can hook PrecacheMDL (good) to make a model changer (e.g. weapons, player models)
doesnt require the forcing or spoofing of protected convars so safer.

**Comment by VeLocityYT** [comment]
https://totalcsgo.com/command/svpure

**Comment by You02** [comment]
> you can hook FindMDL (ghetto)
> or you can hook PrecacheMDL (good) to make a model changer (e.g. weapons, player models)
> doesnt require the forcing or spoofing of protected convars so safer.

But would that work for sounds?
I have no clue lol

**Comment by xAkiraMiura** [comment]
`PlaySoundAsync` or use the game interface for it

**Comment by woah1337** [comment]
umm emitsound is already hooked lol

**Comment by 8cy** [comment]
> https://totalcsgo.com/command/svpure

@VeLocityYT is this a joke

**Comment by xAkiraMiura** [comment]
> 
> 
> > https://totalcsgo.com/command/svpure
> 
> @VeLocityYT is this a joke

sv_pure is forced to be at or below the level of the server, i dont have a source for this but it might be a protected convar
because of it being forced to the level of the server, you have to hook or NOP the function that sets it back down, (or you could set it back every time it is, 10 times a second, super ghetto and super slow)
